/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connectSQL.LopKetNoi;
import javax.swing.JOptionPane;
import module.CheckInPut;
import module.NguoiDung;
import module.TaiKhoan;

/**
 *
 * @author Tuong
 */
public class JPanelCaiDatTaiKhoan extends javax.swing.JPanel {

    private LopKetNoi ketNoiCSDL;
    private NguoiDung nguoiDung;
    TaiKhoan taiKhoan;
    /**
     * Creates new form JPanelCaiDatTaiKhoan
     */
    public JPanelCaiDatTaiKhoan(TaiKhoan taiKhoan) {
        initComponents();
        this.taiKhoan=taiKhoan;
        if (taiKhoan.getMaLoaiTaiKhoan().equals("KH"))
        {
            jButtonDangKyTKQT.setEnabled(false);
        }
        else
        {
            jButtonDangKyTKQT.setEnabled(true);
        }
        ketNoiCSDL = new LopKetNoi();
        nguoiDung=ketNoiCSDL.getThongTinNguoiDung(taiKhoan.getCMND());
        
        txtTen.setText(nguoiDung.getTen());
        txtCMND.setText(nguoiDung.getCMND());
        txtEmail.setText(nguoiDung.getEmail());
        txtSDT.setText(nguoiDung.getSDT());
        txtTenTaiKhoan.setText(taiKhoan.getTenTaiKhoan());
        jpwMatKhau.setText(taiKhoan.getMatKhau());
        
    }


    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbTen = new javax.swing.JLabel();
        jlbCMND = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jlbSDT = new javax.swing.JLabel();
        jlbTenTaiKhoan = new javax.swing.JLabel();
        jlbMatKhau = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtTenTaiKhoan = new javax.swing.JTextField();
        jbtSua = new javax.swing.JButton();
        jbnLuu = new javax.swing.JButton();
        jbtDoiMatKhau = new javax.swing.JButton();
        jpwMatKhau = new javax.swing.JPasswordField();
        jButtonDangKyTKQT = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setRequestFocusEnabled(false);

        jLabel1.setText("Thông tin tài khoản");

        jlbTen.setText("Họ và Tên");

        jlbCMND.setText("CMND");

        jlbEmail.setText("Email");

        jlbSDT.setText("Số điện thoại");

        jlbTenTaiKhoan.setText("Tên tài khoản");

        jlbMatKhau.setText("Mật khẩu");

        txtTen.setEnabled(false);

        txtCMND.setEnabled(false);

        txtEmail.setEnabled(false);

        txtSDT.setEnabled(false);

        txtTenTaiKhoan.setEnabled(false);

        jbtSua.setText("Sửa");
        jbtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSuaActionPerformed(evt);
            }
        });

        jbnLuu.setText("Lưu");
        jbnLuu.setEnabled(false);
        jbnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnLuuActionPerformed(evt);
            }
        });

        jbtDoiMatKhau.setText("Đổi mật khẩu");
        jbtDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDoiMatKhauActionPerformed(evt);
            }
        });

        jpwMatKhau.setEnabled(false);

        jButtonDangKyTKQT.setText("Đăng ký tài khoản Quản trị");
        jButtonDangKyTKQT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangKyTKQTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jbtSua)
                        .addGap(122, 122, 122)
                        .addComponent(jbnLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jbtDoiMatKhau)
                        .addGap(128, 128, 128)
                        .addComponent(jButtonDangKyTKQT))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTen)
                            .addComponent(jlbCMND)
                            .addComponent(jlbEmail)
                            .addComponent(jlbSDT)
                            .addComponent(jlbTenTaiKhoan)
                            .addComponent(jlbMatKhau))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jpwMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                            .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCMND, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDT)
                            .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTen)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCMND)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSDT)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTenTaiKhoan)
                    .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMatKhau)
                    .addComponent(jpwMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSua)
                    .addComponent(jbnLuu)
                    .addComponent(jbtDoiMatKhau)
                    .addComponent(jButtonDangKyTKQT))
                .addGap(20, 20, 20))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jpwMatKhau, txtCMND, txtEmail, txtSDT, txtTen, txtTenTaiKhoan});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSuaActionPerformed
        // TODO add your handling code here:
        txtTen.setEnabled(true);
        txtEmail.setEnabled(true);
        txtSDT.setEnabled(true);
        jbtSua.setEnabled(false);
        jbnLuu.setEnabled(true);
        jbtDoiMatKhau.setEnabled(false);
                
    }//GEN-LAST:event_jbtSuaActionPerformed

    private void jbnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnLuuActionPerformed
        // TODO add your handling code here:
        if (    txtSDT.getText().equals("")
                ||txtTen.getText().equals("")
                ||txtEmail.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Không được để trống bất kì thông tin nào");
        }
        else if (!CheckInPut.checkSDT(txtSDT.getText()))
        {
            JOptionPane.showMessageDialog(this, "Số điện thoại là dãy số gồm 10 hoặc 11 số và bắt đầu bằng 0");
        }
        else if (!CheckInPut.checkTenVietNam(txtTen.getText()))
        {
            JOptionPane.showMessageDialog(this, "Tên không được bao gồm số, ký tự đặc biệt và không vượt quá 50 ký tự");
        }
        else if (!CheckInPut.checkEmail(txtEmail.getText()))
        {
            JOptionPane.showMessageDialog(this, "Email không đúng định dạng và không vượt quá 50 ký tự");
        }
        else
        {
            nguoiDung.setEmail(txtEmail.getText());
            nguoiDung.setSDT(txtSDT.getText());
            nguoiDung.setTen(CheckInPut.chuanHoaTen(txtTen.getText()));
            if (ketNoiCSDL.updateNguoiDung(nguoiDung)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                txtTen.setEnabled(false);
                txtEmail.setEnabled(false);
                txtSDT.setEnabled(false);
                jbtSua.setEnabled(true);
                jbnLuu.setEnabled(false);
                jbtDoiMatKhau.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
            }
        }
        
    }//GEN-LAST:event_jbnLuuActionPerformed

    private void jbtDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDoiMatKhauActionPerformed
        // TODO add your handling code here:
        new JDialogChangePassword(taiKhoan, true).setVisible(true);
        taiKhoan=ketNoiCSDL.getTTTK(taiKhoan.getTenTaiKhoan());   //lấy lai thông tin tài khoản từ CSDL
        jpwMatKhau.setText(taiKhoan.getMatKhau());
    }//GEN-LAST:event_jbtDoiMatKhauActionPerformed

    private void jButtonDangKyTKQTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangKyTKQTActionPerformed
        // TODO add your handling code here:
        new JDialogSignUp(taiKhoan).setVisible(true);
    }//GEN-LAST:event_jButtonDangKyTKQTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDangKyTKQT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton jbnLuu;
    private javax.swing.JButton jbtDoiMatKhau;
    private javax.swing.JButton jbtSua;
    private javax.swing.JLabel jlbCMND;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbMatKhau;
    private javax.swing.JLabel jlbSDT;
    private javax.swing.JLabel jlbTen;
    private javax.swing.JLabel jlbTenTaiKhoan;
    private javax.swing.JPasswordField jpwMatKhau;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
