/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.quanlitau;

import connectSQL.LopKetNoi;
import controller.ChuyenManHinhView;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.Collator;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import module.CheckInPut;
import module.LoaiToa;
import javax.swing.JFrame;
import module.ComboboxToolTipRenderer;
import view.JPanelQuanLiToaTau;


/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelDanhSachToa extends javax.swing.JPanel {

    /**
     * Creates new form JPanelToa
     */
    private DefaultTableModel tbmLoaiToa, tbmToa;
    private int hangDangChonLoaiToa = -1;
    private int hangDangChonToa = -1;
    private LopKetNoi ketNoiCSDL;

    // loai dialog
    private String them = "THÊM";
    private String sua = "SỬA";
    private String thongTin = "THÔNG TIN";
    TableRowSorter<DefaultTableModel> trsToa;
    TableRowSorter<DefaultTableModel> trsLoaiToa;

    public JPanelDanhSachToa() {
        initComponents();
        ketNoiCSDL=new LopKetNoi();
        tbmLoaiToa = (DefaultTableModel) jtbLoaiToa.getModel();
        tbmToa = (DefaultTableModel) jtbToa.getModel();
        loadDSLoaiToaVaoBang(ketNoiCSDL.select("select * from LoaiToa"));
        loadDSToaVaoBang(ketNoiCSDL.select("select * from Toa"));
        trsToa =new TableRowSorter<>(tbmToa);
        trsToa.setComparator(0, new Comparator<String>
        () {
            @Override
            public int compare(String o1, String o2) {
                Collator collator = Collator.getInstance( new Locale("vi","VN"));
                return collator.compare(o1,o2);
            }
        });
        trsToa.setComparator(1, new Comparator<String>
        () {
            @Override
            public int compare(String o1, String o2) {
                Collator collator = Collator.getInstance( new Locale("vi","VN"));
                return collator.compare(o1,o2);
            }
        });
        jtbToa.setRowSorter(trsToa);
        
        trsLoaiToa =new TableRowSorter<>(tbmLoaiToa);
        trsLoaiToa.setComparator(0, new Comparator<String>
        () {
            @Override
            public int compare(String o1, String o2) {
                Collator collator = Collator.getInstance( new Locale("vi","VN"));
                return collator.compare(o1,o2);
            }
        });
        trsLoaiToa.setComparator(1, new Comparator<String>
        () {
            @Override
            public int compare(String o1, String o2) {
                Collator collator = Collator.getInstance( new Locale("vi","VN"));
                return collator.compare(o1,o2);
            }
        });
        jtbLoaiToa.setRowSorter(trsLoaiToa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlLoaiToa = new javax.swing.JDialog((JFrame) null, true);
        jPanel2 = new javax.swing.JPanel();
        jlbTenDialogLoaiToa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXacNhanLoaiToa = new javax.swing.JButton();
        jtfMaLoaiToa = new javax.swing.JTextField();
        jtfTenLoaiToa = new javax.swing.JTextField();
        jlbMaLoaiToa = new javax.swing.JLabel();
        jlbTenLoaiToa = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbbSoChoNgoi = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jtfGiaChoNgoi2 = new javax.swing.JTextField();
        jlbGiaChoNgoi2 = new javax.swing.JLabel();
        jdlToa = new javax.swing.JDialog((JFrame) null, true);
        jPanel3 = new javax.swing.JPanel();
        jlbTenDialogToa = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfMaToa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbbLoaiToa = new javax.swing.JComboBox<>();
        btnXacNhanToa = new javax.swing.JButton();
        jlbMaToa = new javax.swing.JLabel();
        jtfGiaChoNgoi = new javax.swing.JTextField();
        jlbLoaiToa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbGiaChoNgoi = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnToa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbToa = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnThemToa = new javax.swing.JButton();
        btnSuaToa = new javax.swing.JButton();
        btnXoaToa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfTimKiemToa = new javax.swing.JTextField();
        btnTroVeToa = new javax.swing.JButton();
        btnThongTinToa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jpnLoaiToa = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jtbLoaiToa = new javax.swing.JTable();
        jLabel50 = new javax.swing.JLabel();
        btnThemLoaiToa = new javax.swing.JButton();
        btnSuaLoaiToa = new javax.swing.JButton();
        btnXoaLoaiToa = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jtfTimKiemLoaiToa = new javax.swing.JTextField();
        btnTroVeLoaiToa = new javax.swing.JButton();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();

        jdlLoaiToa.setMinimumSize(new java.awt.Dimension(546, 391));
        jdlLoaiToa.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlbTenDialogLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlbTenDialogLoaiToa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDialogLoaiToa.setText("THÊM LOẠI TOA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("MÃ LOẠI:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("TÊN LOẠI TOA");

        btnXacNhanLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnXacNhanLoaiToa.setText("XÁC NHẬN");
        btnXacNhanLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanLoaiToaActionPerformed(evt);
            }
        });

        jtfMaLoaiToa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtfTenLoaiToa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlbMaLoaiToa.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbMaLoaiToa.setForeground(new java.awt.Color(255, 0, 0));
        jlbMaLoaiToa.setText("a");

        jlbTenLoaiToa.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbTenLoaiToa.setForeground(new java.awt.Color(255, 0, 0));
        jlbTenLoaiToa.setText("a");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("SỐ CHỖ NGỒI");

        cbbSoChoNgoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "80", "56", "42", "28" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("GIÁ CHỖ NGỒI");

        jtfGiaChoNgoi2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlbGiaChoNgoi2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbGiaChoNgoi2.setForeground(new java.awt.Color(255, 0, 0));
        jlbGiaChoNgoi2.setText("a");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTenDialogLoaiToa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbMaLoaiToa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfTenLoaiToa)
                    .addComponent(jlbTenLoaiToa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbSoChoNgoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfGiaChoNgoi2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbGiaChoNgoi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfMaLoaiToa))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnXacNhanLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlbTenDialogLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfMaLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMaLoaiToa)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtfTenLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTenLoaiToa)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbbSoChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfGiaChoNgoi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbGiaChoNgoi2)
                .addGap(18, 18, 18)
                .addComponent(btnXacNhanLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdlLoaiToaLayout = new javax.swing.GroupLayout(jdlLoaiToa.getContentPane());
        jdlLoaiToa.getContentPane().setLayout(jdlLoaiToaLayout);
        jdlLoaiToaLayout.setHorizontalGroup(
            jdlLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdlLoaiToaLayout.setVerticalGroup(
            jdlLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlLoaiToaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jdlToa.setMinimumSize(new java.awt.Dimension(646, 393));
        jdlToa.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jlbTenDialogToa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbTenDialogToa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDialogToa.setText("TOA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("MÃ TOA:");

        jtfMaToa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfMaToa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfMaToaFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("LOẠI TOA:");

        cbbLoaiToa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiToaActionPerformed(evt);
            }
        });

        btnXacNhanToa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXacNhanToa.setText("XÁC NHẬN");
        btnXacNhanToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanToaActionPerformed(evt);
            }
        });

        jlbMaToa.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbMaToa.setForeground(new java.awt.Color(255, 0, 0));
        jlbMaToa.setText(" ");

        jtfGiaChoNgoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfGiaChoNgoi.setToolTipText("HỆ SỐ");
        jtfGiaChoNgoi.setEnabled(false);

        jlbLoaiToa.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbLoaiToa.setForeground(new java.awt.Color(255, 0, 0));
        jlbLoaiToa.setText(" ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("GIÁ CHỖ NGỒI:");

        jlbGiaChoNgoi.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbGiaChoNgoi.setForeground(new java.awt.Color(255, 0, 0));
        jlbGiaChoNgoi.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbMaToa, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addComponent(jlbLoaiToa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbGiaChoNgoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnXacNhanToa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfGiaChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMaToa, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTenDialogToa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jlbTenDialogToa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfMaToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jlbMaToa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbbLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbLoaiToa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfGiaChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbGiaChoNgoi)
                .addGap(18, 18, 18)
                .addComponent(btnXacNhanToa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdlToaLayout = new javax.swing.GroupLayout(jdlToa.getContentPane());
        jdlToa.getContentPane().setLayout(jdlToaLayout);
        jdlToaLayout.setHorizontalGroup(
            jdlToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdlToaLayout.setVerticalGroup(
            jdlToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlToaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jpnToa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH TOA");

        jtbToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbToa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ TOA", "MÃ LOẠI TOA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbToa.setGridColor(new java.awt.Color(255, 255, 255));
        jtbToa.setRowHeight(25);
        jtbToa.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jtbToa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbToaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbToaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbToa);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Chức năng");

        btnThemToa.setBackground(new java.awt.Color(255, 255, 255));
        btnThemToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemToa.setText("THÊM");
        btnThemToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemToaActionPerformed(evt);
            }
        });

        btnSuaToa.setBackground(new java.awt.Color(255, 255, 255));
        btnSuaToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaToa.setText("SỬA");
        btnSuaToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaToaActionPerformed(evt);
            }
        });

        btnXoaToa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaToa.setText("XÓA");
        btnXoaToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaToaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tìm kiếm:");

        jtfTimKiemToa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemToaKeyReleased(evt);
            }
        });

        btnTroVeToa.setBackground(new java.awt.Color(255, 255, 255));
        btnTroVeToa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        btnTroVeToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeToaActionPerformed(evt);
            }
        });

        btnThongTinToa.setBackground(new java.awt.Color(255, 255, 255));
        btnThongTinToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongTinToa.setText("THÔNG TIN");
        btnThongTinToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinToaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnToaLayout = new javax.swing.GroupLayout(jpnToa);
        jpnToa.setLayout(jpnToaLayout);
        jpnToaLayout.setHorizontalGroup(
            jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnToaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTimKiemToa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpnToaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnToaLayout.createSequentialGroup()
                        .addComponent(btnTroVeToa)
                        .addGap(396, 396, 396)
                        .addComponent(jLabel1))
                    .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1)
                        .addGroup(jpnToaLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(59, 59, 59)
                            .addComponent(btnThemToa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaToa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(135, 135, 135)
                            .addComponent(btnXoaToa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(130, 130, 130)
                            .addComponent(btnThongTinToa)
                            .addGap(22, 22, 22))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnToaLayout.setVerticalGroup(
            jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnToaLayout.createSequentialGroup()
                .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnToaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnTroVeToa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnToaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnThemToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongTinToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTimKiemToa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("TOA", jpnToa);

        jpnLoaiToa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setText("DANH SÁCH LOẠI TOA");

        jtbLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbLoaiToa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ LOẠI TOA", "TÊN LOẠI TOA", "SỐ CHỖ NGỒI", "GIÁ CHỖ NGỒI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbLoaiToa.setGridColor(new java.awt.Color(255, 255, 255));
        jtbLoaiToa.setRowHeight(25);
        jtbLoaiToa.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jtbLoaiToa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbLoaiToaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbLoaiToaMousePressed(evt);
            }
        });
        jScrollPane13.setViewportView(jtbLoaiToa);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setText("Chức năng");

        btnThemLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnThemLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemLoaiToa.setText("THÊM");
        btnThemLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiToaActionPerformed(evt);
            }
        });

        btnSuaLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnSuaLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaLoaiToa.setText("SỬA");
        btnSuaLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLoaiToaActionPerformed(evt);
            }
        });

        btnXoaLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaLoaiToa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaLoaiToa.setText("XÓA");
        btnXoaLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoaiToaActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setText("Tìm kiếm:");

        jtfTimKiemLoaiToa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemLoaiToaKeyReleased(evt);
            }
        });

        btnTroVeLoaiToa.setBackground(new java.awt.Color(255, 255, 255));
        btnTroVeLoaiToa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        btnTroVeLoaiToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeLoaiToaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnLoaiToaLayout = new javax.swing.GroupLayout(jpnLoaiToa);
        jpnLoaiToa.setLayout(jpnLoaiToaLayout);
        jpnLoaiToaLayout.setHorizontalGroup(
            jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                        .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                            .addComponent(jSeparator26, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator25, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(59, 59, 59)
                        .addComponent(btnThemLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221)
                        .addComponent(btnSuaLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(btnXoaLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                        .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                                .addComponent(btnTroVeLoaiToa)
                                .addGap(369, 369, 369)
                                .addComponent(jLabel49))
                            .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfTimKiemLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpnLoaiToaLayout.setVerticalGroup(
            jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnLoaiToaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnTroVeLoaiToa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoaiToaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel49)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(btnThemLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jpnLoaiToaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTimKiemLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("LOẠI TOA", jpnLoaiToa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbToaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbToaMouseClicked
        // TODO add your handling code here:
        hangDangChonToa = jtbToa.getSelectedRow();
    }//GEN-LAST:event_jtbToaMouseClicked

    private void jtbToaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbToaMousePressed
        // TODO add your handling code here:
        hangDangChonToa = jtbToa.getSelectedRow();
        if (hangDangChonToa != -1) {
            if (evt.getButton() == MouseEvent.BUTTON3) {
                hienThiDialogToa(thongTin);
            }
        }
    }//GEN-LAST:event_jtbToaMousePressed

    private void btnThemToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemToaActionPerformed
        // TODO add your handling code here:
        hienThiDialogToa(them);
    }//GEN-LAST:event_btnThemToaActionPerformed

    private void btnSuaToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonToa < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 dòng trong bảng");
        } else {
            String tempMaToa=jtbToa.getValueAt(jtbToa.getSelectedRow(), 0).toString();
            try {
                ResultSet rs=ketNoiCSDL.select("select * from ChuyenDi where MaToa=?",tempMaToa);
                if (rs.next())
                {
                    JOptionPane.showMessageDialog(this, "Toa này đã được đặt vé, không thể sửa!");
                }
                else
                {
                    hienThiDialogToa(sua);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnSuaToaActionPerformed

    private void btnXoaToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonToa < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 hàng trong bảng");

        } else {
            int input = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (input == JOptionPane.YES_OPTION) {
                String maToa = jtbToa.getValueAt(hangDangChonToa, 0).toString();
                if (LopKetNoi.update("delete from Toa where maToa = ?", maToa)) {
                    tbmToa.removeRow(hangDangChonToa);
                    hangDangChonToa = -1;
                    jtbToa.clearSelection();
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể xóa vì có tàu đang chứa toa");
                }
            }

        }
    }//GEN-LAST:event_btnXoaToaActionPerformed

    private void jtfTimKiemToaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemToaKeyReleased
        // TODO add your handling code here:
        trsToa.setRowFilter(RowFilter.regexFilter(jtfTimKiemToa.getText().toUpperCase().trim()));
    }//GEN-LAST:event_jtfTimKiemToaKeyReleased

    private void btnTroVeToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeToaActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiToaTau()).change();
    }//GEN-LAST:event_btnTroVeToaActionPerformed

    private void btnThongTinToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonToa == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hàng trong bảng");
        } else
            hienThiDialogToa(thongTin);
    }//GEN-LAST:event_btnThongTinToaActionPerformed

    private void jtbLoaiToaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLoaiToaMouseClicked
        // TODO add your handling code here:
        hangDangChonLoaiToa = jtbLoaiToa.getSelectedRow();
    }//GEN-LAST:event_jtbLoaiToaMouseClicked

    private void jtbLoaiToaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLoaiToaMousePressed
        // TODO add your handling code here:
        hangDangChonLoaiToa = jtbLoaiToa.getSelectedRow();
        if (hangDangChonLoaiToa != -1) {
            if (evt.getButton() == MouseEvent.BUTTON3) {
                hienThiDialogLoaiToa(thongTin);
            }
        }
    }//GEN-LAST:event_jtbLoaiToaMousePressed

    private void btnThemLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiToaActionPerformed
        // TODO add your handling code here:
        hienThiDialogLoaiToa(them);
    }//GEN-LAST:event_btnThemLoaiToaActionPerformed

    private void btnSuaLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLoaiToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonLoaiToa < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 dòng trong bảng");
        } else {
            String tempMaLoaiToa=jtbLoaiToa.getValueAt(jtbLoaiToa.getSelectedRow(), 0).toString();
            try {
                ResultSet rs=ketNoiCSDL.select("select MaChuyen from ChuyenDi \n" +
                "where MaToa in (select MaToa from Toa where MaLoaiToa=?)",tempMaLoaiToa);
                if (rs.next())
                {
                    JOptionPane.showMessageDialog(this, "Loại toa này đã xuất hiện trong vé, không thể sửa");
                }
                else
                {
                    hienThiDialogLoaiToa(sua);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnSuaLoaiToaActionPerformed

    private void btnXoaLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoaiToaActionPerformed
        // TODO add your handling code here:
        if (hangDangChonLoaiToa < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 hàng trong bảng");

        } else {
            int input = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (input == JOptionPane.YES_OPTION) {
                String maLoaiToa = jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 0).toString();
                if (ketNoiCSDL.update("delete from LoaiToa where maLoaiToa = ?", maLoaiToa)) {
                    tbmLoaiToa.removeRow(hangDangChonLoaiToa);
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    hangDangChonLoaiToa = -1;
                    jtbLoaiToa.clearSelection();
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể xóa vì loại toa đang thuộc toa");
                }

            }
        }
    }//GEN-LAST:event_btnXoaLoaiToaActionPerformed

    private void jtfTimKiemLoaiToaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemLoaiToaKeyReleased
        // TODO add your handling code here:
        trsLoaiToa.setRowFilter(RowFilter.regexFilter(jtfTimKiemLoaiToa.getText().toUpperCase().trim()));
    }//GEN-LAST:event_jtfTimKiemLoaiToaKeyReleased

    private void btnTroVeLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeLoaiToaActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiToaTau()).change();
    }//GEN-LAST:event_btnTroVeLoaiToaActionPerformed

    private void btnXacNhanLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanLoaiToaActionPerformed
        // TODO add your handling code here:
        String loai = jlbTenDialogLoaiToa.getText();
        if (loai.equals(them)) {
            if (themLoaiToa(ketNoiCSDL)) {
                JOptionPane.showMessageDialog(jdlLoaiToa, "Thêm thành công");
                jtfTenLoaiToa.setText("");
                jtfMaLoaiToa.setText("");
                jlbTenLoaiToa.setText(" ");
                jlbMaLoaiToa.setText(" ");
                jdlLoaiToa.dispose();
                hangDangChonLoaiToa = jtbLoaiToa.getRowCount() - 1;
            } else {
                JOptionPane.showMessageDialog(jdlLoaiToa, "Thêm thất bại");
            }
        } else if (loai.equals(sua)) {
            if (suaLoaiToa()) {
                JOptionPane.showMessageDialog(jdlLoaiToa, "Sửa thành công");
                jdlLoaiToa.dispose();
            } else {
                JOptionPane.showMessageDialog(jdlLoaiToa, "Sửa thất bại");
            }

        } else if (loai.equals(thongTin)) {
            jdlLoaiToa.dispose();
        }
    }//GEN-LAST:event_btnXacNhanLoaiToaActionPerformed

    private void cbbLoaiToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiToaActionPerformed
        // TODO add your handling code here:
        if (cbbLoaiToa.getItemCount() != 0) {
            ResultSet rs = ketNoiCSDL.select("select GiaChoNgoi from LoaiToa where maLoaiToa = ?", cbbLoaiToa.getSelectedItem().toString());
            try {
                if (rs.next()) {
                    jtfGiaChoNgoi.setText(rs.getString(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(JPanelDanhSachToa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_cbbLoaiToaActionPerformed

    private void btnXacNhanToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanToaActionPerformed
        // TODO add your handling code here:
        String loai = jlbTenDialogToa.getText();
        if (loai.equals(them)) {
            if (themToa()) {
                JOptionPane.showMessageDialog(jdlToa, "Thêm thành công");
                setRongCacTruongToa();
                tatThongBaoToa();
                hangDangChonToa = jtbToa.getRowCount() - 1;
                jdlToa.dispose();
            } else {
                JOptionPane.showMessageDialog(jdlToa, "Thêm thất bại");
            }
        } else if (loai.equals(sua)) {
            if (suaToa()) {
                JOptionPane.showMessageDialog(jdlToa, "Sửa thành công");
                jdlToa.dispose();
            } else {
                JOptionPane.showMessageDialog(jdlToa, "Sửa thất bại");
            }

        } else if (loai.equals(thongTin)) {
            jdlToa.dispose();
        }
    }//GEN-LAST:event_btnXacNhanToaActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jtfMaToaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfMaToaFocusLost
        // TODO add your handling code here:
        if(jtfMaToa.getText().length()==0)
        {
            jlbMaToa.setText("Không được để trống");
        }
        else
        {
            jlbMaToa.setText("");
        }
    }//GEN-LAST:event_jtfMaToaFocusLost
    //========================================================code cho loai toa===========================================================
    private void loadDSLoaiToaVaoBang(ResultSet rs) {// maloaitoa, he so
        tbmLoaiToa.setRowCount(0);
        jtbLoaiToa.clearSelection();
        try {
            while (rs.next()) {
                tbmLoaiToa.addRow(new Object[]{rs.getString(1), rs.getString(2),rs.getInt(3),rs.getInt(4)});
            }
        } catch (Exception e) {
            System.out.println("Load ds loai toa vao bang that bai");
        }
    }


    private boolean kiemTraThemLoaiToa() {
        String maLoaiToa = jtfMaLoaiToa.getText().trim();
        if (!CheckInPut.checkCacLoaiMa(maLoaiToa)) {
            jlbMaLoaiToa.setText("Chỉ chữ cái,số , -, khoảng trắng và không rỗng");
        } else {
            try {
                ResultSet rs = LopKetNoi.select("select maLoaiToa from LoaiToa where maLoaiToa = ?", maLoaiToa);
                if (rs.next()) {
                    jlbMaLoaiToa.setText("Mã loại toa đã tồn tại");
                } else {
                    jlbMaLoaiToa.setText(" ");
                    kiemTraGiaChoNgoi();
                }
            } catch (Exception e) {
                System.out.println("Kiem tra them loai toa that bai");
            }
        }
        

        if (jlbMaLoaiToa.getText().equals(" ") && jlbTenLoaiToa.getText().equals(" ")&&jlbGiaChoNgoi2.getText().equals(" ")) {
            return true;
        } else {
            return false;
        }
    }

    private boolean themLoaiToa(LopKetNoi ketNoiCSDL) {
        if (kiemTraThemLoaiToa()) {
            try {
                String maLoaiToa=jtfMaLoaiToa.getText().trim();
                maLoaiToa=maLoaiToa.toUpperCase();
                String tenLoaiToa=jtfTenLoaiToa.getText().trim();
                ketNoiCSDL.update("insert into LoaiToa values(?,?,?,?)", maLoaiToa,
                        tenLoaiToa,cbbSoChoNgoi.getSelectedItem().toString(),Integer.valueOf(jtfGiaChoNgoi2.getText().toString().trim()));
                tbmLoaiToa.addRow(new Object[]{maLoaiToa,
                        tenLoaiToa,cbbSoChoNgoi.getSelectedItem().toString(),Integer.valueOf(jtfGiaChoNgoi2.getText().toString().trim())});
                // highlight dong cuoi
                int hangCuoi = jtbLoaiToa.getRowCount();
                jtbLoaiToa.scrollRectToVisible(jtbLoaiToa.getCellRect(hangCuoi - 1, 0, true));// di chuyen bang den row cuoi
                jtbLoaiToa.clearSelection();
                jtbLoaiToa.setRowSelectionInterval(hangCuoi - 1, hangCuoi - 1);
                return true;
            } catch (Exception e) {
                System.out.println("Them loai toa that bai");
            }
        }
        return false;
    }

    private boolean suaLoaiToa() {
        if (jlbTenLoaiToa.getText().equals(" ")) {
            try {
                String tenLoaiToa=jtfTenLoaiToa.getText().toString().trim();
                int soChoNgoi=Integer.valueOf(cbbSoChoNgoi.getSelectedItem().toString().trim());
                int giaChoNgoi=Integer.valueOf(jtfGiaChoNgoi2.getText().toString().trim());
                String maLoaiToa=jtfMaLoaiToa.getText().toString();
                ketNoiCSDL.update("update LoaiToa set TenLoaiToa = ?, SoChoNgoi=?, GiaChoNgoi=? where MaLoaiToa=?", tenLoaiToa, soChoNgoi, giaChoNgoi,maLoaiToa);
                jtbLoaiToa.setValueAt(tenLoaiToa, hangDangChonLoaiToa, 1);
                jtbLoaiToa.setValueAt(soChoNgoi, hangDangChonLoaiToa, 2);
                jtbLoaiToa.setValueAt(giaChoNgoi, hangDangChonLoaiToa, 3);
                return true;
            } catch (Exception e) {
                System.out.println("Sua loai toa that bai");
            }
        } else {
            return false;
        }
        return true;
    }

    private void thongTinLoaiToa() {
        jtfMaLoaiToa.setText(jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 0) + "");
        jtfTenLoaiToa.setText(jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 1) + "");
    }

    private void setRongCacTruongLoaiToa() {
        jtfMaLoaiToa.setText("");
        jtfTenLoaiToa.setText("");
        jtfGiaChoNgoi2.setText("");
    }

    private void tatThongBaoLoaiToa() {
        jlbMaLoaiToa.setText(" ");
        jlbTenLoaiToa.setText(" ");
        jlbGiaChoNgoi2.setText(" ");
    }

    private void hienCacTruongLoaiToa() {
        jtfMaLoaiToa.setEditable(true);
        jtfTenLoaiToa.setEditable(true);
    }

    private void anCacTruongLoaiToa() {
        jtfMaLoaiToa.setEditable(false);
        jtfTenLoaiToa.setEditable(false);
    }

    private void hienThiDialogLoaiToa(String loai) {
        setRongCacTruongLoaiToa();
        hienCacTruongLoaiToa();
        tatThongBaoLoaiToa();
        if (loai.equals(them)) {
        } else if (loai.equals(sua)) {
            jtfMaLoaiToa.setText(jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 0) + "");
            jtfMaLoaiToa.setEditable(false);
            jtfTenLoaiToa.setText(jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 1) + "");
            cbbSoChoNgoi.setSelectedItem(jtbLoaiToa.getValueAt(hangDangChonLoaiToa,2));
            jtfGiaChoNgoi2.setText(jtbLoaiToa.getValueAt(hangDangChonLoaiToa, 3)+ "");
        } else if (loai.equals(thongTin)) {
            anCacTruongLoaiToa();
            thongTinLoaiToa();
        }
        jlbTenDialogLoaiToa.setText(loai);
        jdlLoaiToa.setLocationRelativeTo(this);
        jdlLoaiToa.setVisible(true);
    }

    //========================================code cho toa==================================================
    private void loadDSToaVaoBang(ResultSet rs) {// matoa, sochongoi, maloaitoa
        tbmToa.setRowCount(0);
        try {
            while (rs.next()) {
                tbmToa.addRow(new Object[]{rs.getString(1), rs.getString(3)});
            }
        } catch (Exception e) {
            System.out.println("Load ds  toa vao bang that bai");
        }
    }

    private void loadDSLoaiToaVaoCBB(LopKetNoi ketNoiCSDL) {
        cbbLoaiToa.setEnabled(true);
        cbbLoaiToa.removeAllItems();
        ComboboxToolTipRenderer renderer = new ComboboxToolTipRenderer();
        List<String> tooltips=new ArrayList<String>();
        cbbLoaiToa.setRenderer(renderer);
        try {
            ResultSet rs = ketNoiCSDL.select("select MaLoaiToa,TenLoaiToa from LoaiToa order by MaLoaiToa ASC");
            while (rs.next()) {
                cbbLoaiToa.addItem(rs.getString(1));
                tooltips.add(rs.getString(2));
            }
            renderer.setTooltips(tooltips);
        } catch (Exception e) {
            System.out.println("load ds loai toa vao cbb that bai");
        }
    }

    private void kiemTraGiaChoNgoi() {
        if (jtfGiaChoNgoi2.getText().trim().equals("")) {
            jlbGiaChoNgoi2.setText("Không được để trống");
        } else {
            try {
                int giaChoNgoi = Integer.parseInt(jtfGiaChoNgoi2.getText().trim());
                if (giaChoNgoi>0&&giaChoNgoi<=10000000)
                {
                    jlbGiaChoNgoi2.setText(" ");
                }
                else
                {
                    jlbGiaChoNgoi2.setText("Giá chỗ ngồi phải >0 và <=1 triệu");
                }
            } catch (Exception e) {
                jlbGiaChoNgoi2.setText("Phải là một số nguyên nhỏ hơn");
            }
        }
    }

    private boolean kiemTraThemToa() {
        //kiem tra ma toa
        if (jtfMaToa.getText().trim().equals("")) {
            jlbMaToa.setText("Không được để trống");
        } else {
            try {
                ResultSet rs = LopKetNoi.select("select maToa from Toa where maToa", jtfMaToa.getText().trim());
                if (rs.next()) {
                    jlbMaToa.setText("Mã toa đã tồn tại");
                } else {
                    jlbMaToa.setText(" ");
                }

            } catch (Exception e) {
                System.out.println("Kiem tra ma toa that bai");
            }
        }

        // kiem tra GiaChoNgoi
        kiemTraGiaChoNgoi();
        if (jlbMaToa.getText().equals(" ") && jlbGiaChoNgoi.getText().equals(" ")) {
            return true;
        } else {
            return false;
        }

    }

    private boolean themToa() {
        if (kiemTraThemToa()) {
            String maToa=jtfMaToa.getText().trim();
            maToa=maToa.toUpperCase();
            ketNoiCSDL.update("insert into Toa(MaToa,MaLoaiToa) values(?,?)", maToa,
                    cbbLoaiToa.getSelectedItem().toString());
            tbmToa.addRow(new Object[]{maToa,
                 cbbLoaiToa.getSelectedItem().toString()});

            // di chuyen den hang cuoi trong bang
            int hangCuoi = jtbToa.getRowCount();
            jtbToa.scrollRectToVisible(jtbToa.getCellRect(hangCuoi - 1, 0, true));// di chuyen bang den row cuoi
            jtbToa.clearSelection();
            jtbToa.setRowSelectionInterval(hangCuoi - 1, hangCuoi - 1);
            return true;
        } else {
            return false;
        }

    }

    private boolean suaToa() {
        if (jlbGiaChoNgoi.getText().equals(" ")) {
            String maToa = jtfMaToa.getText().trim();
            String maLoaiToa = cbbLoaiToa.getSelectedItem().toString();
            LopKetNoi.update("update Toa set maLoaiToa = ? where maToa = ?",
                    maLoaiToa, maToa);
            jtbToa.setValueAt(maToa, hangDangChonToa, 0);
            jtbToa.setValueAt(maLoaiToa, hangDangChonToa, 1);
        } else {
            return false;
        }
        return true;
    }

    private void thongTinToa() {
        String maToa = jtbToa.getValueAt(hangDangChonToa, 0).toString();
        String maLoaiToa = jtbToa.getValueAt(hangDangChonToa, 1).toString();
        loadDSLoaiToaVaoCBB(ketNoiCSDL);
        cbbLoaiToa.setSelectedItem(jtbToa.getValueAt(hangDangChonToa,1));
        cbbLoaiToa.setEnabled(false);
        jtfMaToa.setText(maToa);
    }

    private void setRongCacTruongToa() {
        jtfMaToa.setText("");
        jtfGiaChoNgoi.setText("20");
        if (cbbLoaiToa.getItemCount() != 0) {
            cbbLoaiToa.setSelectedIndex(0);
        }
    }

    private void tatThongBaoToa() {
        jlbMaToa.setText(" ");
        jlbGiaChoNgoi.setText(" ");
        jlbLoaiToa.setText(" ");
    }

    private void hienCacTruongToa() {
        jtfMaToa.setEditable(true);
        jtfGiaChoNgoi.setEditable(true);
    }

    private void anCacTruongToa() {
        jtfMaToa.setEditable(false);
        jtfGiaChoNgoi.setEditable(false);
    }

    private void hienThiDialogToa(String loai) {
        setRongCacTruongToa();
        hienCacTruongToa();
        tatThongBaoToa();
        if (loai.equals(them)) {
            jtfMaToa.setEditable(true);
            hienCacTruongToa();
            loadDSLoaiToaVaoCBB(ketNoiCSDL);
        } else if (loai.equals(sua)) {
            jtfMaToa.setText(jtbToa.getValueAt(hangDangChonToa, 0) + "");
            jtfMaToa.setEditable(false);
            loadDSLoaiToaVaoCBB(ketNoiCSDL);
            cbbLoaiToa.setSelectedItem(jtbToa.getValueAt(hangDangChonToa,1));
        } else if (loai.equals(thongTin)) {
            thongTinToa();
            anCacTruongToa();
        }
        jlbTenDialogToa.setText(loai);
        jdlToa.setLocationRelativeTo(this);
        jdlToa.setVisible(true);
    }
    //=========================================================================================================

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaLoaiToa;
    private javax.swing.JButton btnSuaToa;
    private javax.swing.JButton btnThemLoaiToa;
    private javax.swing.JButton btnThemToa;
    private javax.swing.JButton btnThongTinToa;
    private javax.swing.JButton btnTroVeLoaiToa;
    private javax.swing.JButton btnTroVeToa;
    private javax.swing.JButton btnXacNhanLoaiToa;
    private javax.swing.JButton btnXacNhanToa;
    private javax.swing.JButton btnXoaLoaiToa;
    private javax.swing.JButton btnXoaToa;
    private javax.swing.JComboBox<String> cbbLoaiToa;
    private javax.swing.JComboBox<String> cbbSoChoNgoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jdlLoaiToa;
    private javax.swing.JDialog jdlToa;
    private javax.swing.JLabel jlbGiaChoNgoi;
    private javax.swing.JLabel jlbGiaChoNgoi2;
    private javax.swing.JLabel jlbLoaiToa;
    private javax.swing.JLabel jlbMaLoaiToa;
    private javax.swing.JLabel jlbMaToa;
    private javax.swing.JLabel jlbTenDialogLoaiToa;
    private javax.swing.JLabel jlbTenDialogToa;
    private javax.swing.JLabel jlbTenLoaiToa;
    private javax.swing.JPanel jpnLoaiToa;
    private javax.swing.JPanel jpnToa;
    private javax.swing.JTable jtbLoaiToa;
    private javax.swing.JTable jtbToa;
    private javax.swing.JTextField jtfGiaChoNgoi;
    private javax.swing.JTextField jtfGiaChoNgoi2;
    private javax.swing.JTextField jtfMaLoaiToa;
    private javax.swing.JTextField jtfMaToa;
    private javax.swing.JTextField jtfTenLoaiToa;
    private javax.swing.JTextField jtfTimKiemLoaiToa;
    private javax.swing.JTextField jtfTimKiemToa;
    // End of variables declaration//GEN-END:variables
}
