/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.quanlilotrinh;

import DungChung.StringDungChung;
import connectSQL.LopKetNoi;
import controller.ChuyenManHinhView;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import module.Chuyen;
import module.ThoiGianHoatDong;
import moduledao.ChuyenDao;
import moduledao.ThoiGianHoatDongDao;
import view.JPanelQuanLiLoTrinh;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelChuyen extends javax.swing.JPanel {

    private float vanToc = 60;
    private ThoiGianHoatDongDao thoiGianDao;
    private DefaultTableModel tbmThoiGian, tbmChuyen;
    //==================================
    private String thongTin = "THÔNG TIN";
    private String them = "THÊM";
    private String sua = "SỬA";
    //================================
    private int hangThoiGian = -1;
    private int hangChuyen = -1;

    /**
     * Creates new form JPanelQuanLiChuyen
     */
    public JPanelChuyen() {
        initComponents();
        thoiGianDao = new ThoiGianHoatDongDao();
        tbmChuyen = (DefaultTableModel) jtbChuyen.getModel();
        dpNgayBatDau.setEnabled(false);
        ChuyenDao.loadDSChuyenVaoBang(LopKetNoi.select("select * from Chuyen"), tbmChuyen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlThongTinThoiGian = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jlbTenDialog = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfMaThoiGian = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfTenThoiGian = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbMaThoiGian = new javax.swing.JLabel();
        jlbTenThoiGian = new javax.swing.JLabel();
        jlbNgayBatDau = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jlbNgayKetThuc = new javax.swing.JLabel();
        btnXacNhanThoiGian = new javax.swing.JButton();
        jdcNgayBatDau = new com.toedter.calendar.JDateChooser();
        jdcNgayKetThuc = new com.toedter.calendar.JDateChooser();
        jdlThongTinChuyen = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jlbTenDialogChuyen = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfMaChuyen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jlbMaTuyen = new javax.swing.JLabel();
        jlbNgayKT = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnXacNhanChuyen = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        cbbTrangThai = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jlbMaChuyen = new javax.swing.JLabel();
        cbbMaTau = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cbbMaTuyen = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        dpNgayBatDau = new com.github.lgooddatepicker.components.DatePicker();
        dpNgayKetThuc = new com.github.lgooddatepicker.components.DatePicker();
        btnLichTrinhTau = new javax.swing.JButton();
        dtpthoiGianKH = new com.github.lgooddatepicker.components.DateTimePicker();
        dtpThoiGianDen = new com.github.lgooddatepicker.components.DateTimePicker();
        btnTramDiQua = new javax.swing.JButton();
        jlbMaTau = new javax.swing.JLabel();
        jlbThoiGianKhoiHanh = new javax.swing.JLabel();
        jdlLichTrinh = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbLichTrinh = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbChuyen = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        cbbTiemKiem = new javax.swing.JComboBox<>();
        cbbSapXep = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnThongTIn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jdlThongTinThoiGian.setMinimumSize(new java.awt.Dimension(500, 511));

        jlbTenDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDialog.setText("THÔNG TIN CHI TIẾT");
        jlbTenDialog.setBackground(new java.awt.Color(102, 255, 255));
        jlbTenDialog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setText("MÃ:");
        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jtfMaThoiGian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setText("TÊN: ");
        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jtfTenThoiGian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setText("NGÀY BẮT ĐẦU:");
        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabel7.setText("NGÀY KẾT THÚC:");
        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jlbMaThoiGian.setText("abc");
        jlbMaThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        jlbMaThoiGian.setForeground(new java.awt.Color(255, 51, 51));

        jlbTenThoiGian.setText("abc");
        jlbTenThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        jlbTenThoiGian.setForeground(new java.awt.Color(255, 51, 51));

        jlbNgayBatDau.setText("abc");
        jlbNgayBatDau.setBackground(new java.awt.Color(255, 255, 255));
        jlbNgayBatDau.setForeground(new java.awt.Color(255, 51, 51));

        jLabel17.setText("Định dạng: dd/MM/yyyy");

        jLabel18.setText("Định dạng: dd/MM/yyyy");

        jlbNgayKetThuc.setText("abc");
        jlbNgayKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        jlbNgayKetThuc.setForeground(new java.awt.Color(255, 51, 51));

        btnXacNhanThoiGian.setText("XÁC NHẬN");
        btnXacNhanThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanThoiGian.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhanThoiGian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanThoiGianActionPerformed(evt);
            }
        });

        jdcNgayBatDau.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayBatDau.setDateFormatString("dd/MM/yyyy");
        jdcNgayBatDau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jdcNgayKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayKetThuc.setDateFormatString("dd/MM/yyyy");
        jdcNgayKetThuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTenDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbTenThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbMaThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfMaThoiGian)
                            .addComponent(jtfTenThoiGian)
                            .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnXacNhanThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlbTenDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfMaThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMaThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtfTenThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTenThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNgayBatDau)
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNgayKetThuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnXacNhanThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout jdlThongTinThoiGianLayout = new javax.swing.GroupLayout(jdlThongTinThoiGian.getContentPane());
        jdlThongTinThoiGian.getContentPane().setLayout(jdlThongTinThoiGianLayout);
        jdlThongTinThoiGianLayout.setHorizontalGroup(
            jdlThongTinThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdlThongTinThoiGianLayout.setVerticalGroup(
            jdlThongTinThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jdlThongTinChuyen.setMinimumSize(new java.awt.Dimension(510, 586));
        jdlThongTinChuyen.setPreferredSize(new java.awt.Dimension(650, 604));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jlbTenDialogChuyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenDialogChuyen.setText("THÔNG TIN CHI TIẾT");
        jlbTenDialogChuyen.setBackground(new java.awt.Color(102, 255, 255));
        jlbTenDialogChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setText("MÃ:");
        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jtfMaChuyen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setText("MÃ TUYẾN:");
        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabel19.setText("NGÀY BẮT ĐẦU:");
        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jlbMaTuyen.setText("a");
        jlbMaTuyen.setBackground(new java.awt.Color(255, 255, 255));
        jlbMaTuyen.setForeground(new java.awt.Color(255, 51, 51));

        jlbNgayKT.setText("a");
        jlbNgayKT.setBackground(new java.awt.Color(255, 255, 255));
        jlbNgayKT.setForeground(new java.awt.Color(255, 51, 51));

        jLabel20.setText("Định dạng: dd/MM/yyyy");

        btnXacNhanChuyen.setText("XÁC NHẬN");
        btnXacNhanChuyen.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhanChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanChuyenActionPerformed(evt);
            }
        });

        jLabel22.setText("TRẠNG THÁI:");
        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đi", "Về" }));
        cbbTrangThai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel21.setText("NGÀY KẾT THÚC:");
        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabel23.setText("Định dạng: dd/MM/yyyy");

        jlbMaChuyen.setText("a");
        jlbMaChuyen.setBackground(new java.awt.Color(255, 255, 255));
        jlbMaChuyen.setForeground(new java.awt.Color(255, 51, 51));

        cbbMaTau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel27.setText("MÃ TÀU:");
        jLabel27.setBackground(new java.awt.Color(204, 204, 204));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        cbbMaTuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbMaTuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaTuyenActionPerformed(evt);
            }
        });

        jLabel24.setText("TG KHỞI HÀNH:");
        jLabel24.setBackground(new java.awt.Color(204, 204, 204));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabel29.setText("TG ĐẾN:");
        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        dpNgayBatDau.setEnabled(false);
        dpNgayBatDau.setToolTipText("dd/MM/yyyy");

        dpNgayKetThuc.setToolTipText("dd/MM/yyyy");

        btnLichTrinhTau.setText("XEM LỊCH TRÌNH");
        btnLichTrinhTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichTrinhTauActionPerformed(evt);
            }
        });

        dtpthoiGianKH.setToolTipText("dd/MM/yyyy hh:mm");

        dtpThoiGianDen.setEnabled(false);
        dtpThoiGianDen.setToolTipText("dd/MM/yyyy");

        btnTramDiQua.setText("XEM TRẠM ĐI QUA");

        jlbMaTau.setText("jLabel12");

        jlbThoiGianKhoiHanh.setText("jLabel12");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTenDialogChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXacNhanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpThoiGianDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpthoiGianKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlbThoiGianKhoiHanh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dpNgayKetThuc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dpNgayBatDau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbMaChuyen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbMaTuyen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfMaChuyen, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbbTrangThai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbNgayKT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbbMaTuyen, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbbMaTau, javax.swing.GroupLayout.Alignment.LEADING, 0, 118, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnLichTrinhTau, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(btnTramDiQua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jlbMaTau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jlbTenDialogChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbMaTau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(btnLichTrinhTau))
                .addGap(3, 3, 3)
                .addComponent(jlbMaTau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbbMaTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTramDiQua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMaTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(dtpthoiGianKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbThoiGianKhoiHanh)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(dtpThoiGianDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel20)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(dpNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(dpNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jlbNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnXacNhanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jdlThongTinChuyenLayout = new javax.swing.GroupLayout(jdlThongTinChuyen.getContentPane());
        jdlThongTinChuyen.getContentPane().setLayout(jdlThongTinChuyenLayout);
        jdlThongTinChuyenLayout.setHorizontalGroup(
            jdlThongTinChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jdlThongTinChuyenLayout.setVerticalGroup(
            jdlThongTinChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jdlLichTrinh.setMinimumSize(new java.awt.Dimension(492, 278));

        jtbLichTrinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LỊCH TRÌNH"
            }
        ));
        jScrollPane2.setViewportView(jtbLichTrinh);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÔNG TIN LỊCH TRÌNH TÀU");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );

        javax.swing.GroupLayout jdlLichTrinhLayout = new javax.swing.GroupLayout(jdlLichTrinh.getContentPane());
        jdlLichTrinh.getContentPane().setLayout(jdlLichTrinhLayout);
        jdlLichTrinhLayout.setHorizontalGroup(
            jdlLichTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlLichTrinhLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdlLichTrinhLayout.setVerticalGroup(
            jdlLichTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlLichTrinhLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN BẢNG CHUYẾN");
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtbChuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ CHUYẾN", "MÃ TÀU", "MÃ TUYẾN", "THỜI GIAN KH", "THỜI GIAN KT", "NGÀY BẮT ĐẦU", "NGÀY KẾT THÚC", "TRẠNG THÁI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbChuyen.setGridColor(new java.awt.Color(255, 255, 255));
        jtbChuyen.setRowHeight(25);
        jtbChuyen.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jtbChuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbChuyenMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbChuyenMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbChuyen);

        jLabel5.setText("Chức năng");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnThem.setText("THÊM");
        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel8.setText("Tìm kiếm:");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyReleased(evt);
            }
        });

        cbbTiemKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cbbSapXep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXepActionPerformed(evt);
            }
        });

        jLabel9.setText("Sắp xếp:");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnThongTIn.setText("THÔNG TIN");
        btnThongTIn.setBackground(new java.awt.Color(255, 255, 255));
        btnThongTIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongTIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(59, 59, 59)
                                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbTiemKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbSapXep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThongTIn, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 32, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongTIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbbTiemKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbChuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbChuyenMouseClicked
        // TODO add your handling code here:
        hangChuyen = jtbChuyen.getSelectedRow();
    }//GEN-LAST:event_jtbChuyenMouseClicked

    private void jtbChuyenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbChuyenMousePressed
        // TODO add your handling code here:
        hangChuyen = jtbChuyen.getSelectedRow();
        if (hangChuyen != -1) {
            if (evt.getButton() == MouseEvent.BUTTON3) {
                hienThiDialogChuyen(thongTin);
            }
        }
    }//GEN-LAST:event_jtbChuyenMousePressed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        hienThiDialogChuyen(them);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (hangChuyen < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 dòng trong bảng");
        } else {
            hienThiDialogChuyen(sua);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (hangChuyen < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 hàng trong bảng");

        } else {
            int input = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (input == JOptionPane.YES_OPTION) {
                String maChuyen = jtbChuyen.getValueAt(hangChuyen, 0).toString();
                boolean kt = ChuyenDao.xoaChuyenTrongDB(maChuyen);
                if (kt) {
                    ChuyenDao.xoaChuyenKhoiBang(hangChuyen, tbmChuyen);
                    hangChuyen = -1;
                    jtbChuyen.clearSelection();
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể xóa vì có tàu đang chạy trên tuyến này");
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jtfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyReleased
        // TODO add your handling code here:

//        if (cbbTiemKiem.getSelectedIndex() == 0) {// tim kiem theo ma tuyen
//            String maTuyen = jtfTimKiem.getText().trim();
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen where maTuyen like ?",
//                "%" + maTuyen + "%"), tbmBangTuyen);
//        } else {// tim kiem theo ten tuyen
//            String tenTuyen = jtfTimKiem.getText().trim();
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen where tenTuyen like ?",
//                "%" + tenTuyen + "%"), tbmBangTuyen);
//        }
    }//GEN-LAST:event_jtfTimKiemKeyReleased

    private void cbbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXepActionPerformed
        // TODO add your handling code here:
//        if (cbbSapXep.getSelectedIndex() == 0) {// sap xep ten tuyen tu a - z
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen order by tentuyen ASC"), tbmBangTuyen);
//        } else {
//            tuyenDao.loadDSTuyenVaoBang(LopKetNoi.select("select * from tuyen order by tentuyen DESC"), tbmBangTuyen);
//        }
    }//GEN-LAST:event_cbbSapXepActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiLoTrinh()).change();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThongTInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTInActionPerformed
        // TODO add your handling code here:
        if (hangChuyen == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hàng trong bảng");
        } else
            hienThiDialogChuyen(thongTin);
    }//GEN-LAST:event_btnThongTInActionPerformed

    private void btnXacNhanThoiGianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanThoiGianActionPerformed
        // TODO add your handling code here:
        String loai = jlbTenDialog.getText();
        xuLiXacNhanThoiGianChuyen(loai);
    }//GEN-LAST:event_btnXacNhanThoiGianActionPerformed

    private void jtfMaTuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaTuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMaTuyenActionPerformed

    private void btnLichTrinhTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichTrinhTauActionPerformed
        // TODO add your handling code here:
        if (cbbMaTau.getItemCount() != 0) {
            ArrayList<String> lichTrinh = ChuyenDao.getLichTrinhTau(cbbMaTau.getSelectedItem().toString());
            DefaultTableModel tbmLichTrinh = (DefaultTableModel) jtbLichTrinh.getModel();
            for (String s : lichTrinh) {
                tbmLichTrinh.addRow(new Object[]{s});
            }
            jdlLichTrinh.setLocationRelativeTo(jdlThongTinChuyen);
            jdlLichTrinh.setVisible(true);
        }
    }//GEN-LAST:event_btnLichTrinhTauActionPerformed

    private void btnXacNhanChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanChuyenActionPerformed
        // TODO add your handling code here:
        xuLiXacNhanThoiGianChuyen(jlbTenDialogChuyen.getText());
    }//GEN-LAST:event_btnXacNhanChuyenActionPerformed

    private void cbbMaTuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaTuyenActionPerformed
        // TODO add your handling code here:
        if (cbbMaTuyen.getItemCount() != 0) {
            String tramBDKT = cbbMaTuyen.getSelectedItem().toString();
            try {
                
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cbbMaTuyenActionPerformed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
          dtpThoiGianDen.setDateTimePermissive(ChuyenDao.getThoiGianKT(cbbMaTuyen.getSelectedItem().toString(),
                dtpthoiGianKH.getDateTimePermissive()));
        dpNgayBatDau.setDate(dtpthoiGianKH.getDateTimePermissive().toLocalDate());
    }//GEN-LAST:event_jPanel3MouseEntered

    //==============================================================================================
    //CHUYEN
//===============================================================================================
    private void loadMaTauVaoCBB() {
        cbbMaTau.removeAllItems();
        try {
            ResultSet rs = LopKetNoi.select("select maTau from Tau");
            while (rs.next()) {
                cbbMaTau.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println("Load ma tau vao cbb that bai");
        }

    }

    private void loadMaTuyenVaoCBB() {
        cbbMaTuyen.removeAllItems();
        try {
            ResultSet rs = LopKetNoi.select("select maTuyen from Tuyen");
            while (rs.next()) {
                cbbMaTuyen.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println("Load ma tuyen vao cbb that bai");
        }

    }

    private void kiemTraMaChuyen() {
        String maChuyen = jtfMaChuyen.getText().trim();
        if (maChuyen.equals("")) {
            jlbMaChuyen.setText("Không được để trống");
        } else {
            if (ChuyenDao.kiemTraMaTrung(maChuyen)) {
                jlbMaChuyen.setText(" ");
            } else {
                jlbMaChuyen.setText("Mã bị trùng");
            }
        }
    }
//    
//    private boolean kiemTraTauChayTrung(){
//        
//    }

    private void kiemTraMaTau() {
        if (cbbMaTau.getItemCount() == 0) {
            jlbMaTau.setText("Hiện chưa có tàu");
        } else {
            jlbMaTau.setText(" ");
        }
    }

    private void kiemTraMaTuyen() {
        if (cbbMaTuyen.getItemCount() == 0) {
            jlbMaTuyen.setText("Hiện chưa có tuyến");
        } else {
            jlbMaTuyen.setText(" ");
        }
    }

    private void kiemTraThoiGianKH() {
        try {
            LocalDateTime thoiGianKH = dtpthoiGianKH.getDateTimeStrict();
            jlbThoiGianKhoiHanh.setText(" ");
        } catch (Exception e) {
            jlbThoiGianKhoiHanh.setText("Vui lòng chọn đầy đủ ngày và giờ");
        }
    }

    private void kiemTraNgayKetThuc() {
        try {
            LocalDate ngayBD = dpNgayBatDau.getDate();
            LocalDate ngayKT = dpNgayKetThuc.getDate();
            if (ngayBD.compareTo(ngayKT) > 0) {
                jlbNgayKT.setText("Ngày bắt đầu phải lớn hơn ngày kết thúc");
            } else {
                if(ngayKT.compareTo(dtpThoiGianDen.getDateTimeStrict().toLocalDate())<0){
                    jlbNgayKT.setText("Ngày kết thúc không được nhỏ hơn ngày của thời gian kết thúc");
                }
                jlbNgayKT.setText(" ");
            }
        } catch (Exception e) {
            System.out.println("Chua co ngay bat dau");
        }

    }

    private boolean kiemTraDuLieuHopLeChuyen() {
        // mã không cách và không được trùng
        kiemTraMaChuyen();
        kiemTraMaTau();
        kiemTraMaTuyen();
        kiemTraThoiGianKH();
        kiemTraNgayKetThuc();
        if (jlbMaChuyen.getText().equals(" ") && jlbMaTau.getText().equals(" ")
                && jlbMaTuyen.getText().equals(" ") && jlbThoiGianKhoiHanh.getText().equals(" ")
                && jlbNgayKT.getText().equals(" ")) {
            return true;
        } else {
            return false;
        }

    }

//    private void loadThoiGianVaoCBB(ResultSet rs, JComboBox cbb) {
//        cbb.removeAllItems();
//        try {
//            while (rs.next()) {
//                String ngayBD = StringDungChung.DateSangString(rs.getDate(1), "dd/MM/yyyy");
//                String ngayKT = StringDungChung.DateSangString(rs.getDate(2), "dd/MM/yyyy");
//                String tam = ngayBD + " đến " + ngayKT;
//                cbb.addItem(tam);
//            }
//        } catch (Exception e) {
//        }
//    }
    private Chuyen getChuyenTuJDL() {
        String maChuyen = jtfMaChuyen.getText().trim();
        String maTau = cbbMaTau.getSelectedItem().toString();
        String maTuyen = cbbMaTuyen.getSelectedItem().toString();
        LocalDateTime tgKhoiHanh = dtpthoiGianKH.getDateTimeStrict();
        LocalDateTime tgKetThuc = ChuyenDao.getThoiGianKT(maTuyen, tgKhoiHanh);
        LocalDate ngayBD = tgKhoiHanh.toLocalDate();
        LocalDate ngayKT = dpNgayKetThuc.getDate();
        String trangThai = cbbTrangThai.getSelectedItem().toString();
        Chuyen chuyen = new Chuyen(maChuyen, maTau, maTuyen, tgKhoiHanh, tgKetThuc, ngayBD, ngayKT, trangThai);
        return chuyen;

    }

    private boolean themChuyen() {
        if (kiemTraDuLieuHopLeChuyen()) {
            Chuyen chuyen = getChuyenTuJDL();
            String kiemTraChuyen = ChuyenDao.kiemTraLichTrinhTau(chuyen);
            if (kiemTraChuyen.equals("true")) {
                JOptionPane.showMessageDialog(jdlThongTinChuyen, "Thêm thành công");
                ChuyenDao.themChuyenVaoDB(chuyen);
                ChuyenDao.themChuyenVaoBang(chuyen, jtbChuyen);
                return true;

            } else {
                JOptionPane.showMessageDialog(jdlThongTinChuyen, kiemTraChuyen);
                return false;
            }

        } else {
            return false;
        }

    }

    private boolean suaChuyen() {
        Chuyen chuyen = getChuyenTuJDL();
        String kiemTra = ChuyenDao.kiemTraLichTrinhTau(chuyen);
        if(kiemTra.equals("true")){
            ChuyenDao.suaChuyenTrongDB(chuyen);
            ChuyenDao.suaChuyenTrongBang(chuyen, hangChuyen, jtbChuyen);
            return true;
        }else{
            JOptionPane.showMessageDialog(jdlThongTinChuyen, kiemTra);
            return false;
        }
    }

    private boolean xoaChuyen() {
        if (ChuyenDao.xoaChuyenTrongDB(jtbChuyen.getValueAt(hangThoiGian, 0).toString())) {
            ChuyenDao.xoaChuyenKhoiBang(hangChuyen, tbmChuyen);
            return true;
        } else {
            return false;
        }

    }

    private void setTatCaTruongRongChuyen() {
        jtfMaChuyen.setText("");
        if (cbbMaTau.getItemCount() != 0) {
            cbbMaTau.setSelectedIndex(0);
        }
        if (cbbMaTuyen.getItemCount() != 0) {
            cbbMaTuyen.setSelectedIndex(0);
        }
        dtpthoiGianKH.setDateTimePermissive(LocalDateTime.now());
        dpNgayBatDau.setDateToToday();
        dpNgayKetThuc.setDateToToday();
        cbbTrangThai.setSelectedIndex(0);
    }

    private void setTatCaThongBaoRongChuyen() {
        jlbMaChuyen.setText(" ");
        jlbMaTau.setText(" ");
        jlbMaTuyen.setText(" ");
        jlbThoiGianKhoiHanh.setText(" ");
        jlbNgayKT.setText(" ");
    }

    private void batTatCaTruongChuyen() {
        jtfMaChuyen.setEditable(true);
        cbbMaTau.setEnabled(true);
        cbbMaTuyen.setEditable(true);
        cbbMaTuyen.setEnabled(true);
        dpNgayKetThuc.setEnabled(true);
        cbbTrangThai.setEnabled(true);
    }

    private void tatTatCaTruongChuyen() {
        jtfMaChuyen.setEditable(false);
        cbbMaTau.setEnabled(false);
        cbbMaTuyen.setEditable(false);
        cbbMaTuyen.setEnabled(false);
        dpNgayKetThuc.setEnabled(false);
        cbbTrangThai.setEnabled(false);
    }

    private void loadDSTauVaoCBB(JComboBox cbb) {
        cbb.removeAllItems();
        ArrayList<String> DS = ChuyenDao.getDSMaTau(LopKetNoi.select("select * from Tau"));
        for (String s : DS) {
            cbb.addItem(s);
        }
    }

    private void loadTramBDKTVaoCBB(JComboBox cbb) {
        cbb.removeAllItems();
        ArrayList<String> DS = ChuyenDao.getDSTramBDVaKetThuc(LopKetNoi.select("select * from Tuyen"));
        for (String s : DS) {
            cbb.addItem(s);
        }
    }

    private void napChuyenVaoDialog(String maChuyen) {
        try {
            ResultSet rs = LopKetNoi.select("select * from Chuyen where maChuyen = ?", maChuyen);
            if (rs.next()) {
                jtfMaChuyen.setText(rs.getString("maChuyen"));
                cbbMaTau.setSelectedItem(rs.getString("maTau"));
                cbbMaTuyen.setSelectedItem(rs.getString("maTuyen"));
                LocalDateTime thoiGianKH = rs.getTimestamp("thoiGianKhoiHanh").toLocalDateTime();
                dtpthoiGianKH.setDateTimePermissive(thoiGianKH);
                LocalDateTime thoiGianDen = ChuyenDao.getThoiGianKT(rs.getString("maTuyen"), thoiGianKH);
                dtpThoiGianDen.setDateTimePermissive(thoiGianDen);// bo rs.getString(5);
                dpNgayBatDau.setDate(thoiGianKH.toLocalDate());
                dpNgayKetThuc.setDate(rs.getDate("ngayKetThuc").toLocalDate());
                cbbTrangThai.setSelectedItem(rs.getString("trangThai"));
            }
        } catch (Exception e) {
        }

    }

    private void hienThiDialogChuyen(String loai) {
        setTatCaThongBaoRongChuyen();
        batTatCaTruongChuyen();
        if (loai.equals(thongTin)) {
            tatTatCaTruongChuyen();
            napChuyenVaoDialog(jtbChuyen.getValueAt(hangChuyen, 0).toString());
        } else if (loai.equals(them)) {
            loadMaTauVaoCBB();
            loadMaTuyenVaoCBB();
            setTatCaTruongRongChuyen();
        } else if (loai.equals(sua)) {
            jtfMaChuyen.setEditable(false);
            napChuyenVaoDialog(jtbChuyen.getValueAt(hangChuyen, 0).toString());
        }
        jlbTenDialogChuyen.setText(loai);
        jdlThongTinChuyen.setLocationRelativeTo(this);
        jdlThongTinChuyen.setVisible(true);
    }

    private void xuLiXacNhanThoiGianChuyen(String loai) {
        if (loai.equals(thongTin)) {
            jdlThongTinChuyen.dispose();
        } else if (loai.equals(them)) {
            if (themChuyen()) {
                setTatCaTruongRongChuyen();
                setTatCaThongBaoRongChuyen();
                hangChuyen = jtbChuyen.getRowCount() - 1;
            } else {
                JOptionPane.showMessageDialog(jdlThongTinChuyen, "Thêm thất bại");
            }
        } else if (loai.equals(sua)) {
            if (suaChuyen()) {
                jdlThongTinChuyen.dispose();
            } else {
                JOptionPane.showMessageDialog(jdlThongTinChuyen, "Sửa thất bại");
            }
        }
    }

//============================================================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLichTrinhTau;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThongTIn;
    private javax.swing.JButton btnTramDiQua;
    private javax.swing.JButton btnXacNhanChuyen;
    private javax.swing.JButton btnXacNhanThoiGian;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMaTau;
    private javax.swing.JComboBox<String> cbbMaTuyen;
    private javax.swing.JComboBox<String> cbbSapXep;
    private javax.swing.JComboBox<String> cbbTiemKiem;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private com.github.lgooddatepicker.components.DatePicker dpNgayBatDau;
    private com.github.lgooddatepicker.components.DatePicker dpNgayKetThuc;
    private com.github.lgooddatepicker.components.DateTimePicker dtpThoiGianDen;
    private com.github.lgooddatepicker.components.DateTimePicker dtpthoiGianKH;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser jdcNgayBatDau;
    private com.toedter.calendar.JDateChooser jdcNgayKetThuc;
    private javax.swing.JDialog jdlLichTrinh;
    private javax.swing.JDialog jdlThongTinChuyen;
    private javax.swing.JDialog jdlThongTinThoiGian;
    private javax.swing.JLabel jlbMaChuyen;
    private javax.swing.JLabel jlbMaTau;
    private javax.swing.JLabel jlbMaThoiGian;
    private javax.swing.JLabel jlbMaTuyen;
    private javax.swing.JLabel jlbNgayBatDau;
    private javax.swing.JLabel jlbNgayKT;
    private javax.swing.JLabel jlbNgayKetThuc;
    private javax.swing.JLabel jlbTenDialog;
    private javax.swing.JLabel jlbTenDialogChuyen;
    private javax.swing.JLabel jlbTenThoiGian;
    private javax.swing.JLabel jlbThoiGianKhoiHanh;
    private javax.swing.JTable jtbChuyen;
    private javax.swing.JTable jtbLichTrinh;
    private javax.swing.JTextField jtfMaChuyen;
    private javax.swing.JTextField jtfMaThoiGian;
    private javax.swing.JTextField jtfTenThoiGian;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
