/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.quanlituyen;

import connectSQL.LopKetNoi;
import controller.ChuyenManHinhView;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;

import java.sql.ResultSet;
import java.text.Collator;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import view.JPanelQuanLiTuyen;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import module.CheckInPut;
import module.Tram;
import module.Tuyen;
import moduledao.TramDao;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelDanhSachTram extends javax.swing.JPanel {

    private TramDao tramDao = new TramDao();
    private LopKetNoi ketNoiCSDL = new LopKetNoi();
    private DefaultTableModel tbmBangTram;
    private int hangDangChon = -1;

    /**
     * Creates new form JPanelDanhSachTram
     */
    public JPanelDanhSachTram() {
        initComponents();
//        disableJTF();
        jtbDanhSachTram.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbmBangTram = (DefaultTableModel) jtbDanhSachTram.getModel();
        tramDao.loadDSTramVaoBang(ketNoiCSDL.select("select * from Tram"), tbmBangTram);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlThemSuaTram = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jlbTenDialog = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbTenTramDialog = new javax.swing.JLabel();
        jtfTenTramDialog = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfDiaChiDialog = new javax.swing.JTextField();
        btnXacNhanDialog = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        cbbTimKiem = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbbSapXep = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbDanhSachTram = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        jdlThemSuaTram.setMinimumSize(new java.awt.Dimension(420, 350));

        jPanel5.setMinimumSize(new java.awt.Dimension(397, 300));

        jlbTenDialog.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlbTenDialog.setForeground(new java.awt.Color(51, 51, 255));
        jlbTenDialog.setText("THÊM TRẠM");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tên trạm:");

        jlbTenTramDialog.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jlbTenTramDialog.setForeground(new java.awt.Color(255, 51, 51));

        jtfTenTramDialog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfTenTramDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfTenTramDialogKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTenTramDialogKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Địa chỉ:");

        jtfDiaChiDialog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfDiaChiDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDiaChiDialogKeyPressed(evt);
            }
        });

        btnXacNhanDialog.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanDialog.setText("XÁC NHẬN");
        btnXacNhanDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanDialogActionPerformed(evt);
            }
        });
        btnXacNhanDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnXacNhanDialogKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbTenDialog)
                .addGap(156, 156, 156))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTenTramDialog)
                            .addComponent(jtfDiaChiDialog)
                            .addComponent(jlbTenTramDialog, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnXacNhanDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTenDialog)
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfTenTramDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTenTramDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfDiaChiDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnXacNhanDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jdlThemSuaTramLayout = new javax.swing.GroupLayout(jdlThemSuaTram.getContentPane());
        jdlThemSuaTram.getContentPane().setLayout(jdlThemSuaTramLayout);
        jdlThemSuaTramLayout.setHorizontalGroup(
            jdlThemSuaTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdlThemSuaTramLayout.setVerticalGroup(
            jdlThemSuaTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("DANH SÁCH TRẠM");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tìm kiếm:");

        jtfTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyReleased(evt);
            }
        });

        cbbTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên trạm" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Sắp xếp:");

        cbbSapXep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên trạm a-z", "Tên trạm z-a" }));
        cbbSapXep.setSelectedItem(null);
        cbbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXepActionPerformed(evt);
            }
        });

        jtbDanhSachTram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbDanhSachTram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên trạm", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDanhSachTram.setGridColor(new java.awt.Color(255, 255, 255));
        jtbDanhSachTram.setRowHeight(25);
        jtbDanhSachTram.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jtbDanhSachTram.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jtbDanhSachTram);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Chức năng:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(235, 235, 235)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(64, 64, 64)
                            .addComponent(btnThem)
                            .addGap(76, 76, 76)
                            .addComponent(btnSua)
                            .addGap(78, 78, 78)
                            .addComponent(btnXoa))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(2, 2, 2)
                            .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(188, 188, 188)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator2)
                        .addComponent(jSeparator1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnSua)
                        .addComponent(btnXoa))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hienThiDialog(String title) {
        jdlThemSuaTram.setLocationRelativeTo(this);
        jdlThemSuaTram.setVisible(true);
        jdlThemSuaTram.setTitle(title);
        jlbTenDialog.setText(title);
        if (title.equals("THÊM TRẠM")) {
            jtfTenTramDialog.setEditable(true);
            jtfDiaChiDialog.setEditable(true);
            jtfTenTramDialog.setText("");
            jtfDiaChiDialog.setText("");
        } else {
            jtfTenTramDialog.setText(jtbDanhSachTram.getValueAt(hangDangChon, 0) + "");
            jtfTenTramDialog.setEnabled(false);
            jtfDiaChiDialog.setText(jtbDanhSachTram.getValueAt(hangDangChon, 1) + "");
        }
    }

    private void capNhatSauKhiThem() {
        jtfTenTramDialog.setText("");
        jtfDiaChiDialog.setText("");
        jlbTenTramDialog.setText("Tên trạm không được rỗng");
        jtfTenTramDialog.requestFocus();
        hangDangChon = jtbDanhSachTram.getRowCount() - 1;
    }

    private void themTram() {
        if (!CheckInPut.checkTenVietNam(jtfTenTramDialog.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
            jtfTenTramDialog.requestFocus();
        } else {
            String tenTram = jtfTenTramDialog.getText().trim().toUpperCase();
            String diaChi = jtfDiaChiDialog.getText().trim();
            //them vao csdl va bang
            Tram tram = new Tram(tenTram, diaChi);
            tramDao.themTramVaoDB(tram);
            tramDao.themTramVaoBang(tram, jtbDanhSachTram);
            JOptionPane.showMessageDialog(jdlThemSuaTram, "Thêm thành công");
            //cap nhat lai cac truong
            capNhatSauKhiThem();
        }
    }

    private void suaTram() {
        String tenTram = jtbDanhSachTram.getValueAt(hangDangChon, 0).toString();
        String diaChi = jtfDiaChiDialog.getText().trim();
        //============================================================
        Tram tram = new Tram(tenTram, diaChi);
        tramDao.suaTramTrongBang(tram, hangDangChon, jtbDanhSachTram);
        tramDao.suaTramTrongDB(tram, ketNoiCSDL);
        //===== cap nhat lai mot so thong tin
        
    }

    private void xoaTram() {
        int input = JOptionPane.showConfirmDialog(this, "Bạn chắn chắn muốn xóa chứ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (input == JOptionPane.YES_OPTION) {
            boolean kt = tramDao.xoaTramTrongDB(jtbDanhSachTram.getValueAt(hangDangChon, 0).toString(), ketNoiCSDL);
            if (kt) {
                tramDao.xoaTramKhoiBang(hangDangChon, tbmBangTram);
                hangDangChon = -1;
                jtbDanhSachTram.clearSelection();
            }else{
                JOptionPane.showMessageDialog(this, "Không thể xóa vì có Tuyến đi qua trạm này hoặc Trạm này đã tồn tại trong bảng Khoảng Cách");
            }

            //===================================
        }
    }
    private void btnXacNhanDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanDialogActionPerformed
        // TODO add your handling code here:
        if (jdlThemSuaTram.getTitle().equalsIgnoreCase("Thêm trạm")) {
            themTram();
            jdlThemSuaTram.dispose();
        } else {
            suaTram();
            jdlThemSuaTram.dispose();
        }
    }//GEN-LAST:event_btnXacNhanDialogActionPerformed

    private void jtfTenTramDialogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTenTramDialogKeyReleased
        // TODO add your handling code here:
        String tenTram = jtfTenTramDialog.getText().toUpperCase();
        if (!tenTram.equals("")) {
            jlbTenTramDialog.setText(" ");
            try {
                ResultSet rs = ketNoiCSDL.select("select * from Tram where tenTram = ?", tenTram);
                if (rs.next()) {
                    jlbTenTramDialog.setText("Tên trạm bị trùng");
                } else {
                    jlbTenTramDialog.setText(" ");
                }
            } catch (Exception e) {
            }
        } else {
            jlbTenTramDialog.setText("Tên trạm không được rỗng");
        }
    }//GEN-LAST:event_jtfTenTramDialogKeyReleased

    private void jtfTenTramDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTenTramDialogKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jtfDiaChiDialog.requestFocus();
        }
    }//GEN-LAST:event_jtfTenTramDialogKeyPressed

    private void jtfDiaChiDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDiaChiDialogKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_UP) {
            jtfTenTramDialog.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnXacNhanDialog.requestFocus();
        }
    }//GEN-LAST:event_jtfDiaChiDialogKeyPressed

    private void btnXacNhanDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnXacNhanDialogKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            themTram();
        }
    }//GEN-LAST:event_btnXacNhanDialogKeyPressed

    private void cbbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXepActionPerformed
        // TODO add your handling code here:
        String loaiSapXep=cbbSapXep.getSelectedItem().toString();
        ArrayList <Tram> DSTramChuaSapXep=new ArrayList<Tram>();
        for (int i=0;i<tbmBangTram.getRowCount();i++)
        {
            Tram tram=new Tram();
            tram.setTenTram(jtbDanhSachTram.getValueAt(i, 0).toString());
            tram.setDiaChi(jtbDanhSachTram.getValueAt(i, 1).toString());
            DSTramChuaSapXep.add(tram);
        }
        if (cbbSapXep.getSelectedIndex()==0)
        {
            Collections.sort(DSTramChuaSapXep, new Comparator<Tram>() {
            @Override
            public int compare(Tram lhs, Tram rhs) {
                Collator collator = Collator.getInstance( new Locale("vi","VN"));
                return collator.compare(lhs.getTenTram(), rhs.getTenTram());
            }
        });
        }
        else if (cbbSapXep.getSelectedIndex()==1)
        {
            Collections.sort(DSTramChuaSapXep, new Comparator<Tram>() {
            @Override
            public int compare(Tram lhs, Tram rhs) {
                // -1 - less than, 1 - greater than, 0 - equal, all inversed for descending
                Collator collator = Collator.getInstance( new Locale("vi","VN"));
                return -1*collator.compare(lhs.getTenTram(), rhs.getTenTram());
            }
        });
        }
        tbmBangTram.setRowCount(0);
        for (Tram i : DSTramChuaSapXep) {
            tbmBangTram.addRow(new Object[]{i.getTenTram(),i.getDiaChi()});
//                tbmBangTram.addRow(new Object[]{i.getTenTram()});
        }
    }//GEN-LAST:event_cbbSapXepActionPerformed

    private void jtfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyReleased
        // TODO add your handling code here:
        if (cbbTimKiem.getSelectedIndex() == 0) {// tim kiem theo ma tuyen
                        String tenTram = jtfTimKiem.getText().trim();
                        tramDao.loadDSTramVaoBang(LopKetNoi.select("select * from Tram where TenTram like ?",
                                "%" + tenTram + "%"),tbmBangTram);
                }
    }//GEN-LAST:event_jtfTimKiemKeyReleased

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        hangDangChon=jtbDanhSachTram.getSelectedRow();
        if (hangDangChon == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng để xóa");
        } else {
            xoaTram();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // kiem tra rang buoc
        hangDangChon=jtbDanhSachTram.getSelectedRow();
        if (hangDangChon == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng muốn sửa");
        } else
        {
            String tempTenTram=jtbDanhSachTram.getValueAt(hangDangChon, 0).toString();
            try {
                ResultSet rs=ketNoiCSDL.select("select * from TuyenDiQuaTram where TenTram=?",tempTenTram);
                if (rs.next())
                {
                    JOptionPane.showMessageDialog(this, "Đang có Tuyến đi qua Trạm này, không thể sửa!");
                }
                else
                {
                    ResultSet rs2=ketNoiCSDL.select("select * from KhoangCachTram where TenTramNay=? or TenTramKia=?",tempTenTram,tempTenTram);
                    if (rs2.next())
                    {
                        JOptionPane.showMessageDialog(this, "Trạm này đang có khoảng cách với 1 Trạm khác, không thể sửa!");
                    }
                    else
                    {
                        hienThiDialog("SỬA TRẠM");
                    }
                }
            } catch (Exception e) {
                System.out.println("Lỗi lúc bấm nút sửa");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // kiem tra cac rang buoc
        hienThiDialog("THÊM TRẠM");
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiTuyen()).change();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXacNhanDialog;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbSapXep;
    private javax.swing.JComboBox<String> cbbTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JDialog jdlThemSuaTram;
    private javax.swing.JLabel jlbTenDialog;
    private javax.swing.JLabel jlbTenTramDialog;
    private javax.swing.JTable jtbDanhSachTram;
    private javax.swing.JTextField jtfDiaChiDialog;
    private javax.swing.JTextField jtfTenTramDialog;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
