/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.quanlituyen;

import com.github.lgooddatepicker.components.TimePickerSettings;
import connectSQL.LopKetNoi;
import controller.ChuyenManHinhView;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.Collator;
import java.util.Comparator;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import view.JPanelQuanLiTuyen;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import module.CheckInPut;
import module.Tram;
import moduledao.TramDao;


/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelDanhSachTram extends javax.swing.JPanel {

    private TramDao tramDao = new TramDao();
    private LopKetNoi ketNoiCSDL = new LopKetNoi();
    private DefaultTableModel tbmBangTram;
    private DefaultTableModel tbmBangKCTram;
    private int hangDangChon = -1;
    private int hangDangChonKCTram = -1;
    private TimePickerSettings timeSettings;
    TableRowSorter<DefaultTableModel> trsKCTram;
    TableRowSorter<DefaultTableModel> trsTram;
    /**
     * Creates new form JPanelDanhSachTram
     */
    public JPanelDanhSachTram() {
        timeSettings = new TimePickerSettings();
        timeSettings.use24HourClockFormat();
        initComponents();
        jtbDanhSachTram.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbmBangTram = (DefaultTableModel) jtbDanhSachTram.getModel();
        tbmBangKCTram=(DefaultTableModel) jtbKhoangCachTram.getModel();
        trsKCTram =new TableRowSorter<>(tbmBangKCTram);
        trsKCTram.setComparator(0, new Comparator<String>
        () {
            @Override
            public int compare(String o1, String o2) {
                Collator collator = Collator.getInstance( new Locale("vi","VN"));
                return collator.compare(o1,o2);
            }
        });
        trsKCTram.setComparator(1, new Comparator<String>
        () {
            @Override
            public int compare(String o1, String o2) {
                Collator collator = Collator.getInstance( new Locale("vi","VN"));
                return collator.compare(o1,o2);
            }
        });
        jtbKhoangCachTram.setRowSorter(trsKCTram);
        trsTram =new TableRowSorter<>(tbmBangTram);
        trsTram.setComparator(0, new Comparator<String>
        () {
            @Override
            public int compare(String o1, String o2) {
                Collator collator = Collator.getInstance( new Locale("vi","VN"));
                return collator.compare(o1,o2);
            }
        });
        trsKCTram.setComparator(1, new Comparator<String>
        () {
            @Override
            public int compare(String o1, String o2) {
                Collator collator = Collator.getInstance( new Locale("vi","VN"));
                return collator.compare(o1,o2);
            }
        });
        jtbDanhSachTram.setRowSorter(trsTram);
        tramDao.loadDSTramVaoBang(LopKetNoi.select("select * from Tram"), tbmBangTram);
        loadDSKCTramVaoBang(LopKetNoi.select("select * from KhoangCachTram"), tbmBangKCTram);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlThemSuaTram = new javax.swing.JDialog((JFrame)null, true);
        jPanel5 = new javax.swing.JPanel();
        jlbTenDialog = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbTenTramDialog = new javax.swing.JLabel();
        jtfTenTramDialog = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfDiaChiDialog = new javax.swing.JTextField();
        btnXacNhanDialog = new javax.swing.JButton();
        jdlThemSuaKCTram = new javax.swing.JDialog((JFrame)null, true);
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnXacNhanDialog1 = new javax.swing.JButton();
        jComboBoxTenTramNay = new javax.swing.JComboBox<>();
        jComboBoxTenTramKia = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        timePickerKCTRam = new com.github.lgooddatepicker.components.TimePicker(timeSettings);
        jlbTenDialogKCTram = new javax.swing.JLabel();
        jSpinnerSoNgay = new javax.swing.JSpinner();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbDanhSachTram = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtfTimKiemKCTram = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbKhoangCachTram = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        jdlThemSuaTram.setMinimumSize(new java.awt.Dimension(420, 350));

        jPanel5.setMinimumSize(new java.awt.Dimension(397, 300));

        jlbTenDialog.setText("THÊM TRẠM");
        jlbTenDialog.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlbTenDialog.setForeground(new java.awt.Color(51, 51, 255));

        jLabel8.setText("Tên trạm:");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jlbTenTramDialog.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jlbTenTramDialog.setForeground(new java.awt.Color(255, 51, 51));

        jtfTenTramDialog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfTenTramDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfTenTramDialogKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTenTramDialogKeyReleased(evt);
            }
        });

        jLabel9.setText("Địa chỉ:");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtfDiaChiDialog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfDiaChiDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDiaChiDialogKeyPressed(evt);
            }
        });

        btnXacNhanDialog.setText("XÁC NHẬN");
        btnXacNhanDialog.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanDialogActionPerformed(evt);
            }
        });
        btnXacNhanDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnXacNhanDialogKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbTenDialog)
                .addGap(156, 156, 156))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTenTramDialog)
                            .addComponent(jtfDiaChiDialog)
                            .addComponent(jlbTenTramDialog, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnXacNhanDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTenDialog)
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfTenTramDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTenTramDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfDiaChiDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnXacNhanDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jdlThemSuaTramLayout = new javax.swing.GroupLayout(jdlThemSuaTram.getContentPane());
        jdlThemSuaTram.getContentPane().setLayout(jdlThemSuaTramLayout);
        jdlThemSuaTramLayout.setHorizontalGroup(
            jdlThemSuaTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdlThemSuaTramLayout.setVerticalGroup(
            jdlThemSuaTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jdlThemSuaKCTram.setMinimumSize(new java.awt.Dimension(420, 350));

        jPanel6.setMinimumSize(new java.awt.Dimension(397, 300));

        jLabel12.setText("Tên trạm này:");
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel13.setText("Tên trạm kia:");
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnXacNhanDialog1.setText("XÁC NHẬN");
        btnXacNhanDialog1.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhanDialog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanDialog1ActionPerformed(evt);
            }
        });
        btnXacNhanDialog1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnXacNhanDialog1KeyPressed(evt);
            }
        });

        jComboBoxTenTramNay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTenTramNayMouseClicked(evt);
            }
        });

        jLabel1.setText("Khoảng thời gian:");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jlbTenDialogKCTram.setText("THÊM");
        jlbTenDialogKCTram.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbTenDialogKCTram.setForeground(new java.awt.Color(51, 51, 255));

        jSpinnerSoNgay.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnXacNhanDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(jSpinnerSoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timePickerKCTRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxTenTramKia, 0, 196, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTenTramNay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jlbTenDialogKCTram)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlbTenDialogKCTram)
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxTenTramNay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxTenTramKia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timePickerKCTRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerSoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnXacNhanDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jdlThemSuaKCTramLayout = new javax.swing.GroupLayout(jdlThemSuaKCTram.getContentPane());
        jdlThemSuaKCTram.getContentPane().setLayout(jdlThemSuaKCTramLayout);
        jdlThemSuaKCTramLayout.setHorizontalGroup(
            jdlThemSuaKCTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdlThemSuaKCTramLayout.setVerticalGroup(
            jdlThemSuaKCTramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("DANH SÁCH TRẠM");
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel6.setText("Tìm kiếm:");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtfTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyReleased(evt);
            }
        });

        jtbDanhSachTram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbDanhSachTram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên trạm", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDanhSachTram.setGridColor(new java.awt.Color(255, 255, 255));
        jtbDanhSachTram.setRowHeight(25);
        jtbDanhSachTram.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jtbDanhSachTram.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jtbDanhSachTram);

        jLabel3.setText("Chức năng:");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(2, 2, 2)
                                        .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(375, 375, 375)
                                        .addComponent(jLabel2)))
                                .addGap(0, 397, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnThem)
                        .addGap(242, 242, 242)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa)
                        .addGap(142, 142, 142))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnSua)
                        .addComponent(btnXoa))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trạm", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("KHOẢNG CÁCH CÁC TRẠM");
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnThem1.setText("Thêm");
        btnThem1.setBackground(new java.awt.Color(255, 255, 255));
        btnThem1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnSua1.setText("Sửa");
        btnSua1.setBackground(new java.awt.Color(255, 255, 255));
        btnSua1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnXoa1.setText("Xóa");
        btnXoa1.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Tìm kiếm:");
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtfTimKiemKCTram.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfTimKiemKCTram.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKCTramKeyReleased(evt);
            }
        });

        jtbKhoangCachTram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên trạm này", "Tên trạm kia", "Số ngày", "Khoảng thời gian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbKhoangCachTram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbKhoangCachTram.setGridColor(new java.awt.Color(255, 255, 255));
        jtbKhoangCachTram.setRowHeight(25);
        jtbKhoangCachTram.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jtbKhoangCachTram.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jtbKhoangCachTram);
        if (jtbKhoangCachTram.getColumnModel().getColumnCount() > 0) {
            jtbKhoangCachTram.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel5.setText("Chức năng:");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(2, 2, 2)
                                        .addComponent(jtfTimKiemKCTram, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(344, 344, 344)
                                        .addComponent(jLabel4)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnThem1)
                        .addGap(262, 262, 262)
                        .addComponent(btnSua1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                        .addComponent(btnXoa1)
                        .addGap(145, 145, 145))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem1)
                        .addComponent(btnSua1)
                        .addComponent(btnXoa1))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfTimKiemKCTram, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Khoảng Cách Trạm", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hienThiDialog(String title) {
        jdlThemSuaTram.setTitle(title);
        jlbTenDialog.setText(title);
        if (title.equals("THÊM TRẠM")) {
            jtfTenTramDialog.setEditable(true);
            jtfDiaChiDialog.setEditable(true);
            jtfTenTramDialog.setText("");
            jtfDiaChiDialog.setText("");
        } else {
            jtfTenTramDialog.setText(jtbDanhSachTram.getValueAt(hangDangChon, 0) + "");
            jtfTenTramDialog.setEnabled(false);
            jlbTenDialog.setText(" ");
            jtfDiaChiDialog.setText(jtbDanhSachTram.getValueAt(hangDangChon, 1) + "");
        }
        jdlThemSuaTram.setLocationRelativeTo(this);
        jdlThemSuaTram.setVisible(true);
    }
    private void hienThiDialogKCTram(String title) {
        jdlThemSuaKCTram.setTitle(title);
        jlbTenDialogKCTram.setText(title);
        loadDSTramVaoCBB(LopKetNoi.select("select * from Tram"), jComboBoxTenTramNay);
        if (title.equals("THÊM")) {
            jComboBoxTenTramNay.setEnabled(true);
            jComboBoxTenTramKia.setEnabled(true);
        } else {
            jComboBoxTenTramNay.setEnabled(false);
            jComboBoxTenTramKia.setEnabled(false);
            loadDSTramVaoCBB(LopKetNoi.select("select * from Tram"), jComboBoxTenTramKia);
            jComboBoxTenTramNay.setSelectedItem(jtbKhoangCachTram.getValueAt(hangDangChonKCTram, 0) + "");            
            jComboBoxTenTramKia.setSelectedItem(jtbKhoangCachTram.getValueAt(hangDangChonKCTram, 1) + "");
            jSpinnerSoNgay.setValue(Integer.valueOf(jtbKhoangCachTram.getValueAt(hangDangChonKCTram, 2).toString()));
            String strKhoangThoiGian=jtbKhoangCachTram.getValueAt(hangDangChonKCTram, 3).toString();
            timePickerKCTRam.setText(strKhoangThoiGian);
        }
        jdlThemSuaKCTram.setLocationRelativeTo(this);
        jdlThemSuaKCTram.setVisible(true);
    }

    private void capNhatSauKhiThem() {
        jtfTenTramDialog.setText("");
        jtfDiaChiDialog.setText("");
        jlbTenTramDialog.setText("Tên trạm không được rỗng");
        jtfTenTramDialog.requestFocus();
        hangDangChon = jtbDanhSachTram.getRowCount() - 1;
    }

    private void themTram() {
        if (!CheckInPut.checkTenVietNam(jtfTenTramDialog.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
            jtfTenTramDialog.requestFocus();
        } else {
            String tenTram = jtfTenTramDialog.getText().trim().toUpperCase();
            String diaChi = jtfDiaChiDialog.getText().trim();
            //them vao csdl va bang
            Tram tram = new Tram(tenTram, diaChi);
            tramDao.themTramVaoDB(tram);
            tramDao.themTramVaoBang(tram, jtbDanhSachTram);
            JOptionPane.showMessageDialog(jdlThemSuaTram, "Thêm thành công");
            jdlThemSuaTram.dispose();
            //cap nhat lai cac truong
            capNhatSauKhiThem();
        }
    }
    private void themKCTram() {
        String khoangThoiGian=timePickerKCTRam.toString();
        if (jComboBoxTenTramKia.getItemCount()==0) {
            JOptionPane.showMessageDialog(this, "Khoảng cách trạm đã được thêm đầy đủ");
        } 
        else if (khoangThoiGian.equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập thời gian đúng định dạng");
           
        }
        else
        {
            
            LopKetNoi.update("insert into KhoangCachTram values(?,?,?,?)"
                ,jComboBoxTenTramNay.getSelectedItem().toString()
                ,jComboBoxTenTramKia.getSelectedItem().toString()
                ,timePickerKCTRam.toString()
                ,jSpinnerSoNgay.getValue().toString());
            tbmBangKCTram.addRow(new Object[]{jComboBoxTenTramNay.getSelectedItem()
                    ,jComboBoxTenTramKia.getSelectedItem(),jSpinnerSoNgay.getValue().toString(),timePickerKCTRam.toString()});
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            jdlThemSuaKCTram.dispose();
        }
    }
    
    private void suaTram() {
        String tenTram = jtbDanhSachTram.getValueAt(hangDangChon, 0).toString();
        String diaChi = jtfDiaChiDialog.getText().trim();
        //============================================================
        Tram tram = new Tram(tenTram, diaChi);
        tramDao.suaTramTrongBang(tram, hangDangChon, jtbDanhSachTram);
        tramDao.suaTramTrongDB(tram, ketNoiCSDL);
        //===== cap nhat lai mot so thong tin
        
    }

    private void xoaTram() {
        int input = JOptionPane.showConfirmDialog(this, "Bạn chắn chắn muốn xóa chứ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (input == JOptionPane.YES_OPTION) {
            boolean kt = tramDao.xoaTramTrongDB(jtbDanhSachTram.getValueAt(hangDangChon, 0).toString(), ketNoiCSDL);
            if (kt) {
                tramDao.xoaTramKhoiBang(hangDangChon, tbmBangTram);
                hangDangChon = -1;
                jtbDanhSachTram.clearSelection();
            }else{
                JOptionPane.showMessageDialog(this, "Không thể xóa vì có Tuyến đi qua trạm này hoặc Trạm này đã tồn tại trong bảng Khoảng Cách");
            }

            //===================================
        }
    }
    private void btnXacNhanDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanDialogActionPerformed
        // TODO add your handling code here:
        if (jdlThemSuaTram.getTitle().equalsIgnoreCase("Thêm trạm")) {
            themTram();
        } else {
            suaTram();
            jdlThemSuaTram.dispose();
        }
    }//GEN-LAST:event_btnXacNhanDialogActionPerformed

    private void jtfTenTramDialogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTenTramDialogKeyReleased
        // TODO add your handling code here:
        String tenTram = jtfTenTramDialog.getText().toUpperCase();
        if (!tenTram.equals("")) {
            jlbTenTramDialog.setText(" ");
            try {
                ResultSet rs = ketNoiCSDL.select("select * from Tram where tenTram = ?", tenTram);
                if (rs.next()) {
                    jlbTenTramDialog.setText("Tên trạm bị trùng");
                } else {
                    jlbTenTramDialog.setText(" ");
                }
            } catch (Exception e) {
            }
        } else {
            jlbTenTramDialog.setText("Tên trạm không được rỗng");
        }
    }//GEN-LAST:event_jtfTenTramDialogKeyReleased

    private void jtfTenTramDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTenTramDialogKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jtfDiaChiDialog.requestFocus();
        }
    }//GEN-LAST:event_jtfTenTramDialogKeyPressed

    private void jtfDiaChiDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDiaChiDialogKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_UP) {
            jtfTenTramDialog.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnXacNhanDialog.requestFocus();
        }
    }//GEN-LAST:event_jtfDiaChiDialogKeyPressed

    private void btnXacNhanDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnXacNhanDialogKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            themTram();
        }
    }//GEN-LAST:event_btnXacNhanDialogKeyPressed
    public void loadDSKCTramVaoBang(ResultSet rs, DefaultTableModel model) {
        model.setRowCount(0);
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2),rs.getString(4),rs.getString(3).substring(0, rs.getString(3).length()-11)});
            }
        } catch (SQLException ex) {
            System.out.println("Load KC Trạm bị lỗi");
        }
    }
    public void loadDSTramVaoCBB(ResultSet rs, JComboBox cbb1) {
        cbb1.removeAllItems();
        try {
            while (rs.next()) {
                cbb1.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            System.out.println("Load DS Trạm vào CBB KCTram bị lỗi");
        }
    }
    
    private void jtfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyReleased
        // TODO add your handling code here:
        trsTram.setRowFilter(RowFilter.regexFilter(jtfTimKiem.getText().toUpperCase().trim()));
    }//GEN-LAST:event_jtfTimKiemKeyReleased

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        hangDangChon=jtbDanhSachTram.getSelectedRow();
        if (hangDangChon == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng để xóa");
        } else {
            xoaTram();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // kiem tra rang buoc
        hangDangChon=jtbDanhSachTram.getSelectedRow();
        if (hangDangChon == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng muốn sửa");
        } else
        {
//            String tempTenTram=jtbDanhSachTram.getValueAt(hangDangChon, 0).toString();
//            try {
//                ResultSet rs=ketNoiCSDL.select("select * from ChuyenDi where TenTramDi=? or TenTramDen=?",tempTenTram,tempTenTram);
//                if (rs.next())
//                {
//                    JOptionPane.showMessageDialog(this, "Đang có Tuyến đi qua Trạm này, không thể sửa!");
//                }
//                else
//                {
                    
                        hienThiDialog("SỬA TRẠM");
                    
//                }
//            } catch (Exception e) {
//                System.out.println("Lỗi lúc bấm nút sửa");
//                e.printStackTrace();
//            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // kiem tra cac rang buoc
        hienThiDialog("THÊM TRẠM");
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiTuyen()).change();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelQuanLiTuyen()).change();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
        hienThiDialogKCTram("THÊM");
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        // kiem tra rang buoc
        hangDangChonKCTram=jtbKhoangCachTram.getSelectedRow();
        if (hangDangChonKCTram == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng muốn sửa");
        } else
        {
            hienThiDialogKCTram("SỬA");
        }
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        hangDangChonKCTram=jtbKhoangCachTram.getSelectedRow();
        if (hangDangChonKCTram == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng muốn sửa");
        } else
        {
            ResultSet rs=LopKetNoi.select("select table1.MaTuyen,table1.ThoiGianHieuChinh\n" +
            "from TuyenDiQuaTram as table1\n" +
            "join TuyenDiQuaTram as table2\n" +
            "on table1.MaTuyen=table2.MaTuyen and table1.ThoiGianHieuChinh=table2.ThoiGianHieuChinh\n" +
            "and table1.TenTram =? and table2.TenTram =?\n" +
            "and table2.STT-table1.STT=1", jtbKhoangCachTram.getValueAt(hangDangChonKCTram, 0)
                    , jtbKhoangCachTram.getValueAt(hangDangChonKCTram, 1));
            try {
                if (rs.next())
            {
                JOptionPane.showMessageDialog(this, "Có tuyến dùng khoảng cách trạm này, không thể xoá");
            }
            else
            {
                LopKetNoi.update("delete from KhoangCachTram where tenTramNay = ? and tenTramKia=?"
                    , jtbKhoangCachTram.getValueAt(hangDangChonKCTram, 0)
                    , jtbKhoangCachTram.getValueAt(hangDangChonKCTram, 1));
                tbmBangKCTram.removeRow(hangDangChonKCTram);
                JOptionPane.showMessageDialog(this, "Xoá thành công!");
            }
            } catch (Exception e) {
                System.out.println("Xoá KCT bị lỗi");
            }
        }
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void jtfTimKiemKCTramKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKCTramKeyReleased
        // TODO add your handling code here: 
        trsKCTram.setRowFilter(RowFilter.regexFilter(jtfTimKiemKCTram.getText().toUpperCase().trim()));
    }//GEN-LAST:event_jtfTimKiemKCTramKeyReleased

    private void btnXacNhanDialog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanDialog1ActionPerformed
        // TODO add your handling code here:
        if (jdlThemSuaKCTram.getTitle().equals("THÊM")) {
            themKCTram();
        } else {
            String tenTramNay=jComboBoxTenTramNay.getSelectedItem().toString();
            String tenTramKia=jComboBoxTenTramKia.getSelectedItem().toString();
            String khoangCach=timePickerKCTRam.toString();
            String soNgay=jSpinnerSoNgay.getValue().toString();
            if (LopKetNoi.update("update KhoangCachTram set khoangCach=?, soNgay=?\n" +
            "where TenTramNay=? and TenTramKia=?",khoangCach,soNgay,tenTramNay,tenTramKia))
            {
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                jtbKhoangCachTram.setValueAt(soNgay, hangDangChonKCTram, 2);
                jtbKhoangCachTram.setValueAt(khoangCach, hangDangChonKCTram, 3);
                jdlThemSuaKCTram.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Đã có vé đi qua 2 trạm này, không thể sửa!");
            }
        }
    }//GEN-LAST:event_btnXacNhanDialog1ActionPerformed

    private void btnXacNhanDialog1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnXacNhanDialog1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanDialog1KeyPressed

    private void jComboBoxTenTramNayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTenTramNayMouseClicked
        // TODO add your handling code here:
        if (jdlThemSuaKCTram.getTitle().equals("THÊM"))
        {
            loadDSTramVaoCBB(LopKetNoi.select("select TenTram from Tram\n" +
"where TenTram not in (select TenTramKia from KhoangCachTram\n" +
"where TenTramNay=?) and TenTram!=?", jComboBoxTenTramNay.getSelectedItem().toString(), jComboBoxTenTramNay.getSelectedItem().toString()), jComboBoxTenTramKia);
        }
    }//GEN-LAST:event_jComboBoxTenTramNayMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXacNhanDialog;
    private javax.swing.JButton btnXacNhanDialog1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxTenTramKia;
    private javax.swing.JComboBox<String> jComboBoxTenTramNay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jSpinnerSoNgay;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jdlThemSuaKCTram;
    private javax.swing.JDialog jdlThemSuaTram;
    private javax.swing.JLabel jlbTenDialog;
    private javax.swing.JLabel jlbTenDialogKCTram;
    private javax.swing.JLabel jlbTenTramDialog;
    private javax.swing.JTable jtbDanhSachTram;
    private javax.swing.JTable jtbKhoangCachTram;
    private javax.swing.JTextField jtfDiaChiDialog;
    private javax.swing.JTextField jtfTenTramDialog;
    private javax.swing.JTextField jtfTimKiem;
    private javax.swing.JTextField jtfTimKiemKCTram;
    private com.github.lgooddatepicker.components.TimePicker timePickerKCTRam;
    // End of variables declaration//GEN-END:variables
}
