/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.datve;


import connectSQL.LopKetNoi;
import controller.ChuyenManHinhView;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import view.JPanelDatVe;
import module.TaiKhoan;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelDanhSachVe extends javax.swing.JPanel {

    private LopKetNoi ketNoiCSDL;
    private DefaultTableModel jtbVeModel;
    int hangDangChon=-1;
    SimpleDateFormat formatter;
    TaiKhoan taiKhoan;
    /**
     * Creates new form JPanelDanhSachTuyen
     */
    public JPanelDanhSachVe(TaiKhoan taiKhoan) {
        initComponents();
        this.taiKhoan=taiKhoan;
        formatter= new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
        ketNoiCSDL=new LopKetNoi();
        jtbVeModel = (DefaultTableModel) jtbVe.getModel();
        if (taiKhoan.getMaLoaiTaiKhoan().equals("KH"))
        {
            loadDSVeVaoBang(ketNoiCSDL.select("select * from Ve where TenTaiKhoan=?",taiKhoan.getTenTaiKhoan()), jtbVeModel);
        }
        else
        {
            loadDSVeVaoBang(ketNoiCSDL.select("select * from Ve"), jtbVeModel);
        }
    }



    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbVe = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        cbbTimKiem = new javax.swing.JComboBox<>();
        cbbSapXep = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfTen = new javax.swing.JTextField();
        jtfSoDinhDanh = new javax.swing.JTextField();
        jtfTenTramDi = new javax.swing.JTextField();
        jtfMaTau = new javax.swing.JTextField();
        jtfMaToa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfTenTramDen = new javax.swing.JTextField();
        jtfTenTramDi_ChieuVe = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfTenTramDen_ChieuVe = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfMaTau_ChieuVe = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfMaToa_ChieuVe = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtfThoiGianDi = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtfThoiGianDen = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtfChoNgoi = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH VÉ");

        jtbVe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Vé", "Thời Gian Lên Tàu", "Tên Tài Khoản", "Chỗ Ngồi", "Thời Gian Đến", "Giá", "Khứ Hồi", "Tên Loại Vé", "Mã Chuyến"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbVe.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtbVe.setGridColor(new java.awt.Color(255, 255, 255));
        jtbVe.setRowHeight(25);
        jtbVe.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jtbVe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbVeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbVe);
        if (jtbVe.getColumnModel().getColumnCount() > 0) {
            jtbVe.getColumnModel().getColumn(0).setResizable(false);
            jtbVe.getColumnModel().getColumn(1).setResizable(false);
            jtbVe.getColumnModel().getColumn(1).setPreferredWidth(163);
            jtbVe.getColumnModel().getColumn(2).setResizable(false);
            jtbVe.getColumnModel().getColumn(2).setPreferredWidth(120);
            jtbVe.getColumnModel().getColumn(3).setResizable(false);
            jtbVe.getColumnModel().getColumn(4).setResizable(false);
            jtbVe.getColumnModel().getColumn(4).setPreferredWidth(163);
            jtbVe.getColumnModel().getColumn(5).setResizable(false);
            jtbVe.getColumnModel().getColumn(5).setPreferredWidth(141);
            jtbVe.getColumnModel().getColumn(6).setResizable(false);
            jtbVe.getColumnModel().getColumn(7).setResizable(false);
            jtbVe.getColumnModel().getColumn(7).setPreferredWidth(120);
            jtbVe.getColumnModel().getColumn(8).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Chức năng");

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tìm kiếm:");

        jtfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyReleased(evt);
            }
        });

        cbbTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Vé", "CMND" }));

        cbbSapXep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã vé a-z", "Mã vé z-a" }));
        cbbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXepActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Sắp xếp:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_arrow_back_black_24dp_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("THÔNG TIN KHÁCH");

        jLabel3.setText(" THÔNG TIN CHUYẾN ĐI");

        jLabel4.setText("Tên:");

        jLabel6.setText("Số định danh:");

        jLabel10.setText("Tên Trạm Đi:");

        jLabel11.setText("Mã Tàu:");

        jLabel12.setText("Mã Toa:");

        jtfTen.setEditable(false);

        jtfSoDinhDanh.setEditable(false);

        jtfTenTramDi.setEditable(false);

        jtfMaTau.setEditable(false);

        jtfMaToa.setEditable(false);

        jLabel13.setText("Tên Trạm Đến:");

        jtfTenTramDen.setEditable(false);

        jtfTenTramDi_ChieuVe.setEditable(false);

        jLabel14.setText("Tên Trạm Đi:");

        jLabel15.setText("Tên Trạm Đến:");

        jtfTenTramDen_ChieuVe.setEditable(false);

        jLabel16.setText("Mã Tàu:");

        jtfMaTau_ChieuVe.setEditable(false);

        jLabel17.setText("Mã Toa:");

        jtfMaToa_ChieuVe.setEditable(false);

        jLabel18.setText(" THÔNG TIN CHUYẾN VỀ");

        jLabel19.setText("Thời Gian Đi:");

        jtfThoiGianDi.setEditable(false);

        jLabel20.setText("THÔNG TIN VÉ KHỨ HỒI");

        jLabel21.setText("Thời Gian Đến:");

        jtfThoiGianDen.setEditable(false);

        jLabel22.setText("Chỗ Ngồi:");

        jtfChoNgoi.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1394, 1394, 1394)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(392, 392, 392)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtfTen, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jtfSoDinhDanh))
                                    .addGap(101, 101, 101)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtfMaToa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jtfMaTau)
                                                    .addComponent(jtfTenTramDen)
                                                    .addComponent(jtfTenTramDi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jLabel3)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(102, 102, 102)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnXoa)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel22)
                                                .addComponent(jLabel21)
                                                .addComponent(jLabel19))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jtfThoiGianDen))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jtfChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jtfThoiGianDi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(43, 43, 43)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel17))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtfMaToa_ChieuVe, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jtfMaTau_ChieuVe)
                                                    .addComponent(jtfTenTramDen_ChieuVe)
                                                    .addComponent(jtfTenTramDi_ChieuVe, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jLabel18)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 251, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jtfTenTramDi_ChieuVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jtfTenTramDen_ChieuVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jtfMaTau_ChieuVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jtfThoiGianDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jtfThoiGianDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jtfChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfMaToa_ChieuVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jtfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jtfSoDinhDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jtfTenTramDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jtfTenTramDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jtfMaTau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfMaToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnXoa)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadThongTinKhach()
    {
        int maVe=-1;
        try {
            maVe=Integer.valueOf(jtbVeModel.getValueAt(hangDangChon, 0).toString());
        } catch (Exception e) {
            System.out.println("Lỗi chuyển mã vé thành số");
        }
        java.sql.Timestamp thoiGianDi=null;
        try {
            SimpleDateFormat formatter=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
            thoiGianDi=new java.sql.Timestamp(formatter.parse(jtbVeModel.getValueAt(hangDangChon, 1).toString()).getTime());
        } catch (Exception e) {
            System.out.println("Parse Thời gian đi từ bảng bị lỗi");
        }
        try {
            ResultSet rs=ketNoiCSDL.select("select * from Ve where MaVe=? and ThoiGianLenTau=?",maVe,thoiGianDi);
            if (rs.next())
            {
                jtfTen.setText(rs.getString(12));
                jtfSoDinhDanh.setText(rs.getString(13));
            }
        } catch (Exception e) {
            System.out.println("Không tìm được tên và số định danh trong DB");
        }
    }

    private void loadDSVeVaoBang(ResultSet rs,DefaultTableModel model)
    {
        model.setRowCount(0);
        int dem=0;
        try {
            while (rs.next())
            {
                jtbVeModel.addRow(new Object[] {"","","","","","","","",""});
                jtbVeModel.setValueAt(rs.getInt(1), dem, 0);
                jtbVeModel.setValueAt(rs.getTimestamp(2), dem, 1);
                jtbVeModel.setValueAt(rs.getString(3), dem, 2);
                jtbVeModel.setValueAt(rs.getInt(4), dem, 3);
                jtbVeModel.setValueAt(rs.getTimestamp(5), dem, 4);
                jtbVeModel.setValueAt(rs.getInt(8), dem, 5);
                jtbVeModel.setValueAt(rs.getBoolean(9), dem, 6);
                jtbVeModel.setValueAt(rs.getString(10), dem, 7);
                jtbVeModel.setValueAt(rs.getInt(11), dem, 8);
                dem++;
            }
        } catch (Exception e) {
            System.out.println("Không có vé nào");
        }
    }
    public void setAllTextFieldEmpty()
    {
        jtfTen.setText("");
        jtfSoDinhDanh.setText("");
        jtfTenTramDi.setText("");
        jtfTenTramDen.setText("");
        jtfMaTau.setText("");
        jtfMaToa.setText("");
        jtfThoiGianDi.setText("");
        jtfThoiGianDen.setText("");
        jtfChoNgoi.setText("");
        jtfTenTramDi_ChieuVe.setText("");
        jtfTenTramDen_ChieuVe.setText("");
        jtfMaTau_ChieuVe.setText("");
        jtfMaToa_ChieuVe.setText("");
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (hangDangChon < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng! Vui lòng chọn 1 hàng trong bảng");

        } else {
            int input = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (input == JOptionPane.YES_OPTION) {
                int maVe = Integer.valueOf(jtbVe.getValueAt(hangDangChon, 0).toString());
                String thoiGianDi=jtbVe.getValueAt(hangDangChon,1).toString();
                int maChuyen = Integer.valueOf(jtbVe.getValueAt(hangDangChon, 8).toString());
                boolean kt = xoaVeTrongDB(maVe,thoiGianDi,maChuyen,ketNoiCSDL);
                if (kt) {
                    jtbVeModel.removeRow(hangDangChon);
                    hangDangChon = -1;
                    jtbVe.clearSelection();
                    setAllTextFieldEmpty();
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể xóa vì có tàu đang chạy trên tuyến này");
                }
            }
        }

    }//GEN-LAST:event_btnXoaActionPerformed
//    private void xoaTramKhoiBang(int hangDangChon,DefaultTableModel model)
//    {
//        model.removeRow(hangDangChon);
//    }
    private boolean xoaVeTrongDB(int maVe,String thoiGianDi,int maChuyen,LopKetNoi ketNoiCSDL)
    {
        boolean deletedVe=false;
        try {
            java.sql.Timestamp tsThoiGianDi=new java.sql.Timestamp(formatter.parse(thoiGianDi).getTime());
            ketNoiCSDL.update("delete from Ve_KhuHoi where MaVe_ChieuDi=? and ThoiGianLenTau_ChieuDi=?",maVe,tsThoiGianDi);
            deletedVe=ketNoiCSDL.update("delete from Ve where maVe=? and ThoiGianLenTau=?",maVe,tsThoiGianDi);
            ketNoiCSDL.update("delete from ChuyenDi where MaChuyen=?",maChuyen);
        } catch (Exception e) {
            System.out.println("lỗi xoá Vé, Ve_KhuHoi, ChuyenDi");
        }
        return deletedVe;
    }
    private void jtfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyReleased
        // TODO add your handling code here:
        if (taiKhoan.getMaLoaiTaiKhoan().equals("KH"))
            {
                if (cbbTimKiem.getSelectedIndex() == 0) {// tim kiem theo ma tuyen
                    String maVe = jtfTimKiem.getText().trim();
                    loadDSVeVaoBang(ketNoiCSDL.select("select * from Ve where TenTaiKhoan=? and maVe like ?",
                            taiKhoan.getTenTaiKhoan(),"%" + maVe + "%"), jtbVeModel);
                } else {// tim kiem theo ten tuyen
                    String soDinhDanh = jtfTimKiem.getText().trim();
                    loadDSVeVaoBang(ketNoiCSDL.select("select * from Ve where TenTaiKhoan=? and SoDinhDanh like ?",
                            taiKhoan.getTenTaiKhoan(),"%" + soDinhDanh + "%"), jtbVeModel);
                }
            }
        else
        {
            if (cbbTimKiem.getSelectedIndex() == 0) {// tim kiem theo ma tuyen
            String maTuyen = jtfTimKiem.getText().trim();
            loadDSVeVaoBang(ketNoiCSDL.select("select * from Ve where maVe like ?",
                    "%" + maTuyen + "%"), jtbVeModel);
            } else {// tim kiem theo ten tuyen
                String tenTuyen = jtfTimKiem.getText().trim();
                loadDSVeVaoBang(ketNoiCSDL.select("select * from Ve where SoDinhDanh like ?",
                        "%" + tenTuyen + "%"), jtbVeModel);
            }
        }
    }//GEN-LAST:event_jtfTimKiemKeyReleased

    private void cbbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXepActionPerformed
        // TODO add your handling code here:
        if (taiKhoan.getMaLoaiTaiKhoan().equals("KH"))
            {
                if (cbbSapXep.getSelectedIndex() == 0) {// sap xep ten tuyen tu a - z
                    loadDSVeVaoBang(ketNoiCSDL.select("select * from Ve where TenTaiKhoan=? order by MaVe ASC", taiKhoan.getTenTaiKhoan()), jtbVeModel);
                } else {
                    loadDSVeVaoBang(ketNoiCSDL.select("select * from Ve where TenTaiKhoan=? order by MaVe DESC",taiKhoan.getTenTaiKhoan()), jtbVeModel);
                }
            }
        else
        {
             if (cbbSapXep.getSelectedIndex() == 0) {// sap xep ten tuyen tu a - z
            loadDSVeVaoBang(ketNoiCSDL.select("select * from Ve order by MaVe ASC"), jtbVeModel);
            } else {
                loadDSVeVaoBang(ketNoiCSDL.select("select * from Ve order by MaVe DESC"), jtbVeModel);
            }
        }
    }//GEN-LAST:event_cbbSapXepActionPerformed

    private void jtbVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbVeMouseClicked
        // TODO add your handling code here:
        hangDangChon = jtbVe.getSelectedRow();
        if (hangDangChon != -1) {
            loadThongTinKhach();
            loadThongTinChuyenDi(ketNoiCSDL, Integer.valueOf(jtbVeModel.getValueAt(hangDangChon, 8).toString()));
            if (jtbVeModel.getValueAt(hangDangChon, 6).toString().equals("true"))
            {
                loadThongTinVeKhuHoi(ketNoiCSDL, Integer.valueOf(jtbVeModel.getValueAt(hangDangChon, 0).toString()), jtbVeModel.getValueAt(hangDangChon, 1).toString());
            }
            else
            {
                jtfThoiGianDi.setText("");
                jtfThoiGianDen.setText("");
                jtfChoNgoi.setText("");
                jtfTenTramDi_ChieuVe.setText("");
                jtfTenTramDen_ChieuVe.setText("");
                jtfMaTau_ChieuVe.setText("");
                jtfMaToa_ChieuVe.setText("");
            }
        }
    }//GEN-LAST:event_jtbVeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChuyenManHinhView(this, new JPanelDatVe(taiKhoan)).change();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void loadThongTinVeKhuHoi(LopKetNoi ketNoiCSDL, int maVe, String thoiGianLenTau_ChieuDi)
    {
        try {
            
            java.sql.Timestamp tsThoiGianLenTau_ChieuDi=new java.sql.Timestamp(formatter.parse(thoiGianLenTau_ChieuDi).getTime());
        } catch (Exception e) {
            System.out.println("Lỗi parse thoiGianLenTau_ChieuDi");
        }
        try {
            ResultSet rs = ketNoiCSDL.select("select * from Ve_KhuHoi where MaVe_ChieuDi=? and ThoiGianLenTau_ChieuDi=?",maVe,thoiGianLenTau_ChieuDi);
            if (rs.next())
            {
                String thoiGianDi=rs.getTimestamp(2).toString();  
                thoiGianDi=thoiGianDi.substring(0, thoiGianDi.length()-5);  //bỏ giây và mili giây
                jtfThoiGianDi.setText(thoiGianDi);
                String thoiGianDen=rs.getTimestamp(3).toString();  
                thoiGianDen=thoiGianDen.substring(0, thoiGianDen.length()-5);  //bỏ giây và mili giây
                jtfThoiGianDen.setText(thoiGianDen);
                jtfChoNgoi.setText(String.valueOf(rs.getInt(4)));
                loadThongTinChuyenVe(ketNoiCSDL, rs.getInt(5));
            }
        } catch (Exception e) {
            System.out.println("Lỗi load thông tin khách!");
        }
    }
    private void loadThongTinChuyenDi(LopKetNoi ketNoiCSDL, int maChuyen)
    {
        try {
            ResultSet rs = ketNoiCSDL.select("select * from ChuyenDi\n" +
            "join TauChayTuyen\n" +
            "on ChuyenDi.ID_TCT=TauChayTuyen.ID_TCT\n" +
            "and ChuyenDi.MaChuyen=?",maChuyen);
            if (rs.next())
            {
                jtfTenTramDi.setText(rs.getString("TenTramDi"));
                jtfTenTramDen.setText(rs.getString("TenTramDen"));
                jtfMaTau.setText(rs.getString("MaTau")+"_"+rs.getString("ThoiGianHieuChinhTau"));
                jtfMaTau.setToolTipText(rs.getString("MaTau")+"_"+rs.getString("ThoiGianHieuChinhTau"));
                jtfMaToa.setText(rs.getString("MaToa"));                
            }
        } catch (Exception e) {
            System.out.println("Lỗi load thông tin chuyến!");
        }
    }
    private void loadThongTinChuyenVe(LopKetNoi ketNoiCSDL, int maChuyen)
    {
        try {
            ResultSet rs = ketNoiCSDL.select("select * from ChuyenDi\n" +
            "join TauChayTuyen\n" +
            "on ChuyenDi.ID_TCT=TauChayTuyen.ID_TCT\n" +
            "and ChuyenDi.MaChuyen=?",maChuyen);
            if (rs.next())
            {
                jtfTenTramDi_ChieuVe.setText(rs.getString("TenTramDi"));
                jtfTenTramDen_ChieuVe.setText(rs.getString("TenTramDen"));
                jtfMaTau_ChieuVe.setText(rs.getString("MaTau")+"_"+rs.getString("ThoiGianHieuChinhTau"));
                jtfMaTau_ChieuVe.setToolTipText(rs.getString("MaTau")+"_"+rs.getString("ThoiGianHieuChinhTau"));
                jtfMaToa_ChieuVe.setText(rs.getString("MaToa"));                
            }
        } catch (Exception e) {
            System.out.println("Lỗi load thông tin chuyến!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbSapXep;
    private javax.swing.JComboBox<String> cbbTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jtbVe;
    private javax.swing.JTextField jtfChoNgoi;
    private javax.swing.JTextField jtfMaTau;
    private javax.swing.JTextField jtfMaTau_ChieuVe;
    private javax.swing.JTextField jtfMaToa;
    private javax.swing.JTextField jtfMaToa_ChieuVe;
    private javax.swing.JTextField jtfSoDinhDanh;
    private javax.swing.JTextField jtfTen;
    private javax.swing.JTextField jtfTenTramDen;
    private javax.swing.JTextField jtfTenTramDen_ChieuVe;
    private javax.swing.JTextField jtfTenTramDi;
    private javax.swing.JTextField jtfTenTramDi_ChieuVe;
    private javax.swing.JTextField jtfThoiGianDen;
    private javax.swing.JTextField jtfThoiGianDi;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
