/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.datve;
import connectSQL.LopKetNoi;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import module.Tram;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import module.Tau;
import module.Tuyen;
import javax.swing.JTabbedPane;
import module.Toa;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import module.TaiKhoan;
import module.TauChayTuyen;
import module.TuyenDiQuaTram;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */

public class JPanelTimVeTau extends javax.swing.JPanel {

    LopKetNoi ketNoiCSDL;
    ArrayList<Tram> DSTram;
    ArrayList<TuyenDiQuaTram[]> DSTuyen;  //Dùng Tuyến Đi Qua Trạm mà không dùng Tuyến là vì để lấy được Mã trạm mà khách cần lên, VÌ TÌM TUYẾN THEO TRẠM
    ArrayList<TuyenDiQuaTram[]> DSTuyen_ChieuVe;
    ArrayList<TauChayTuyen> DSTau;//DS tàu thoả mãn có thời gian đến phù hợp với yêu cầu của khách nhưng chưa chắc đến Trạm mà khách lên kịp ngày
    ArrayList<TauChayTuyen> DSTauPhuHop;//DS tàu chắc chắn đến trạm đúng ngày mà khách yêu cầu
    ArrayList<TauChayTuyen> DSTauPhuHop_ChieuVe;
    ArrayList<Toa> DSToa;
    ArrayList<Toa> DSToaCuaTatCaTau;
    ArrayList<Toa> DSToaCuaTatCaTau_ChieuVe;
    //TreeMap<String,JTabbedPane> JTabbedPaneDSTau;
    TreeMap<String,NewJPanel> JTabbedPaneDSToa;
    DefaultTableModel model;
    int maVeChieuDi; //lưu để tạo vé Khứ hồi, vì thêm vào csdl rồi sẽ khó lấy ra 1 cách chính xác,
    Timestamp thoiGianLenTauChieuDi;// ví dụ như chạy nhiều luồng thì lấy maVeChieuDi sẽ không chính xác
    public TaiKhoan taiKhoan;
    javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel jLabelChieuVe;
    /**
     * Creates new form PanelTimVeTau
     */
    public JPanelTimVeTau(TaiKhoan taiKhoan) {
        initComponents();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabelChieuVe = new javax.swing.JLabel();
        jLabelChieuVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelChieuVe.setForeground(new java.awt.Color(0, 0, 255));

        this.taiKhoan=taiKhoan;
        //JTabbedPaneDSTau=new TreeMap<String,JTabbedPane>();
        JTabbedPaneDSToa=new TreeMap<String, NewJPanel>();
        DSTauPhuHop=new ArrayList<TauChayTuyen>();
        DSTauPhuHop_ChieuVe=new ArrayList<TauChayTuyen>();
        DSToaCuaTatCaTau= new ArrayList<Toa>();
        DSToaCuaTatCaTau_ChieuVe= new ArrayList<Toa>();
        ketNoiCSDL=new LopKetNoi();
        DSTram=ketNoiCSDL.getDSTram();
        for (Tram i: DSTram)
        {
            jComboBoxGaDi.addItem(i.getTenTram());
            jComboBoxGaDen.addItem(i.getTenTram());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupChonChieuDi = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonTimVe = new javax.swing.JButton();
        jRadioButton1Chieu = new javax.swing.JRadioButton();
        jRadioButtonKhuHoi = new javax.swing.JRadioButton();
        jFormattedTextFieldNgayDi = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldNgayVe = new javax.swing.JFormattedTextField();
        jComboBoxGaDi = new javax.swing.JComboBox<>();
        jComboBoxGaDen = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jlbThoiGianDi = new javax.swing.JLabel();
        jButtonDatVe1 = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabelChieuDi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("TÌM VÉ TÀU");

        jLabel2.setText("Ga đi");

        jLabel3.setText("Ga đến");

        jButtonTimVe.setText("Tìm vé");
        jButtonTimVe.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonTimVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimVeActionPerformed(evt);
            }
        });

        buttonGroupChonChieuDi.add(jRadioButton1Chieu);
        jRadioButton1Chieu.setText("1 chiều");
        jRadioButton1Chieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ChieuActionPerformed(evt);
            }
        });

        buttonGroupChonChieuDi.add(jRadioButtonKhuHoi);
        jRadioButtonKhuHoi.setText("Khứ hồi");
        jRadioButtonKhuHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonKhuHoiActionPerformed(evt);
            }
        });

        jFormattedTextFieldNgayDi.setEnabled(false);

        jLabel5.setText("Ngày đi");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        jLabel6.setText("Ngày về");

        jFormattedTextFieldNgayVe.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Xoá 1 vé trong bảng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonDatVe1.setText("Đặt vé");
        jButtonDatVe1.setEnabled(false);
        jButtonDatVe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatVe1ActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        jLabelChieuDi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelChieuDi.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jRadioButton1Chieu)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonTimVe, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jComboBoxGaDi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jComboBoxGaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jRadioButtonKhuHoi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jFormattedTextFieldNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jFormattedTextFieldNgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDatVe1)
                                .addGap(69, 69, 69)
                                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabelChieuDi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(387, 387, 387)
                                        .addComponent(jlbThoiGianDi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(643, 643, 643))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel2)
                            .addGap(8, 8, 8)
                            .addComponent(jLabel3)
                            .addGap(25, 25, 25)
                            .addComponent(jRadioButton1Chieu)
                            .addGap(2, 2, 2)
                            .addComponent(jLabel5)
                            .addGap(15, 15, 15)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1)
                            .addGap(10, 10, 10)
                            .addComponent(jlbThoiGianDi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBoxGaDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(jComboBoxGaDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButtonKhuHoi)
                            .addGap(2, 2, 2)
                            .addComponent(jFormattedTextFieldNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(jFormattedTextFieldNgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonDatVe1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonTimVe, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jButtonReset)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelChieuDi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonKhuHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonKhuHoiActionPerformed
        // TODO add your handling code here:
        jFormattedTextFieldNgayDi.setEnabled(true);
        jFormattedTextFieldNgayVe.setEnabled(true);
        jLabelChieuDi.setText("Chiều đi");
        jLabelChieuVe.setText("Chiều về");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chiều","Mã Tàu", "Mã Toa", "Ghế Số", "Thời Gian Đi", "Thời Gian Đến"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(163);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(163);
        }
        //giao diện chọn ghế
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelChieuVe, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelChieuDi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 608, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelChieuDi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelChieuVe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);
    }//GEN-LAST:event_jRadioButtonKhuHoiActionPerformed

    private void jButtonTimVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimVeActionPerformed
        // TODO add your handling code here:
        String tenTramDi=(String)jComboBoxGaDi.getSelectedItem();
        String tenTramDen=(String)jComboBoxGaDen.getSelectedItem(); 
        String strNgayDi=jFormattedTextFieldNgayDi.getText();
        String strNgayVe=jFormattedTextFieldNgayVe.getText();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        try {
            formatter.parse(strNgayDi);
            DSTuyen=ketNoiCSDL.getTuyenPhuHop(tenTramDi, tenTramDen);
            if (DSTuyen.size()==0)
            {
                JOptionPane.showMessageDialog(this, "Không có tàu nào chạy "+jLabelChieuDi.getText().toLowerCase()+" trong ngày đã chọn!");
                if (jLabelChieuDi.getText().equals("")) 
                {
                    jFormattedTextFieldNgayDi.setEnabled(true);
                }
                else
                {
                    jFormattedTextFieldNgayDi.setEnabled(true);
                    jFormattedTextFieldNgayVe.setEnabled(true);
                }
                jButtonTimVe.setEnabled(true);
                jButtonDatVe1.setEnabled(false);
            }
            else
            {
                jRadioButton1Chieu.setEnabled(false);
                jRadioButtonKhuHoi.setEnabled(false);
                jFormattedTextFieldNgayDi.setEnabled(false);
                jFormattedTextFieldNgayVe.setEnabled(false);
                jButtonTimVe.setEnabled(false);
                jButtonDatVe1.setEnabled(true);
                model=(DefaultTableModel) jTable1.getModel();
                for (TuyenDiQuaTram[] i:DSTuyen)
                {
                    DSTau=ketNoiCSDL.getTauTheoMaTuyen(i[0].getMaTuyen(),strNgayDi); //DS Tàu có khoảng thời gian phù hợp
                    if (DSTau.size()==0)
                {
                    jRadioButton1Chieu.setEnabled(true);
                    jRadioButtonKhuHoi.setEnabled(true);
                    jFormattedTextFieldNgayDi.setEnabled(true);
                    jFormattedTextFieldNgayVe.setEnabled(true);
                    jButtonTimVe.setEnabled(true);
                    jButtonDatVe1.setEnabled(false);
                    JOptionPane.showMessageDialog(this, "Không tìm được tàu phù hợp");
                }
                    boolean timDuocItNhat1Tau=false;
                    for (TauChayTuyen j:DSTau)
                {
                    TauChayTuyen tauPhuHop=ketNoiCSDL.getTauPhuHop(i,j.getMaTau(), j.getThoiGianKhoiHanh(), strNgayDi);
                    if (tauPhuHop!=null)
                    {
                    timDuocItNhat1Tau=true;
                    DSTauPhuHop.add(tauPhuHop);
                    String thoiGianDi=tauPhuHop.getThoiGianDenTramDi().toString();  
                    String thoiGianDen=tauPhuHop.getThoiGianDen().toString();
                    thoiGianDi=thoiGianDi.substring(0, thoiGianDi.length()-5);  //bỏ giây và mili giây
                    thoiGianDen=thoiGianDen.substring(0, thoiGianDen.length()-5);  //bỏ giây và mili giây
                    JTabbedPane jTabbedPaneTau=new JTabbedPane();
                    //JTabbedPaneDSTau.put(tauPhuHop.getMaTau(),jTabbedPaneTau);
                    jTabbedPane1.add(tauPhuHop.getMaTau(),jTabbedPaneTau);
                    DSToa=ketNoiCSDL.getToaTheoMaTau(tauPhuHop.getMaTau());
                    for (Toa l:DSToa)
                    {   
                        DSToaCuaTatCaTau.add(l);
                        ArrayList<Integer> DSGheDaDat= ketNoiCSDL.getChoNgoiDaDat(tauPhuHop.getMaTau(), tauPhuHop.getThoiGianKhoiHanh(), l.getMaToa(), l.getThoiGianThemToa());
                        NewJPanel newJPanel;
                        switch (l.getSoChoNgoi()) {
                            case 80:
                                newJPanel=new JPanelNgoiCung80(tauPhuHop.getMaTau(),l.getMaToa(),thoiGianDi,thoiGianDen,model,jLabelChieuVe.getText(),DSGheDaDat);
                                jTabbedPaneTau.add(l.getMaToa(),newJPanel);
                                JTabbedPaneDSToa.put(l.getMaToa()+" "+thoiGianDi,newJPanel);
                                break;
                            case 56:
                                newJPanel=new JPanelNgoiMem56(tauPhuHop.getMaTau(),l.getMaToa(),thoiGianDi,thoiGianDen,model,jLabelChieuVe.getText(),DSGheDaDat);
                                JTabbedPaneDSToa.put(l.getMaToa()+" "+thoiGianDi,newJPanel);
                                jTabbedPaneTau.add(l.getMaToa(),newJPanel);
                                break;
                            case 42:
                                newJPanel=new JPanelGiuongNamKhoang642(tauPhuHop.getMaTau(),l.getMaToa(),thoiGianDi,thoiGianDen,model,jLabelChieuVe.getText(),DSGheDaDat);
                                JTabbedPaneDSToa.put(l.getMaToa()+" "+thoiGianDi,newJPanel);
                                jTabbedPaneTau.add(l.getMaToa(),newJPanel);
                                break;
                            case 28:
                                newJPanel=new JPanelGiuongNamKhoang428(tauPhuHop.getMaTau(),l.getMaToa(),thoiGianDi,thoiGianDen,model,jLabelChieuVe.getText(),DSGheDaDat);
                                JTabbedPaneDSToa.put(l.getMaToa()+" "+thoiGianDi,newJPanel);
                                jTabbedPaneTau.add(l.getMaToa(),newJPanel);
                                break;
                        }
                        }
                    }
                    else
                    {
                        if (timDuocItNhat1Tau=false) 
                        {
                            if (jLabelChieuDi.getText().equals("")) JOptionPane.showMessageDialog(this, "Không có tàu nào chạy trong ngày đã chọn!");
                            else
                            {
                                JOptionPane.showMessageDialog(this, "Không có tàu nào chạy "+jLabelChieuDi.getText().toLowerCase()+" trong ngày đã chọn!");
                                jRadioButton1Chieu.setEnabled(true);
                                jRadioButtonKhuHoi.setEnabled(true);
                            }
                            jButtonTimVe.setEnabled(true);
                            jButtonDatVe1.setEnabled(false);
                        }
                    }
                }
                }
            }
            if (jRadioButtonKhuHoi.isSelected())
            {    
                formatter.parse(strNgayVe);
                String tempTenTram;
                tempTenTram=tenTramDi;
                tenTramDi=tenTramDen;
                tenTramDen=tempTenTram;
                DSTuyen_ChieuVe=ketNoiCSDL.getTuyenPhuHop(tenTramDi, tenTramDen);
            if (DSTuyen_ChieuVe.size()==0)
            {
                JOptionPane.showMessageDialog(this, "Không có tàu nào chạy "+jLabelChieuDi.getText().toLowerCase()+" trong ngày đã chọn!");
                jFormattedTextFieldNgayDi.setEnabled(true);
                jFormattedTextFieldNgayVe.setEnabled(true);
                jButtonTimVe.setEnabled(true);
                jButtonDatVe1.setEnabled(false);
            }
            else
            {
                strNgayDi=strNgayVe;
                jRadioButton1Chieu.setEnabled(false);
                jRadioButtonKhuHoi.setEnabled(false);
                jFormattedTextFieldNgayDi.setEnabled(false);
                jFormattedTextFieldNgayVe.setEnabled(false);
                jButtonTimVe.setEnabled(false);
                jButtonDatVe1.setEnabled(true);
                model=(DefaultTableModel) jTable1.getModel();
                for (TuyenDiQuaTram[] i:DSTuyen_ChieuVe)
                {
                    DSTau=ketNoiCSDL.getTauTheoMaTuyen(i[0].getMaTuyen(),strNgayDi); //DS Tàu có khoảng thời gian phù hợp
                    if (DSTau.size()==0)
                {
                    jRadioButton1Chieu.setEnabled(true);
                    jRadioButtonKhuHoi.setEnabled(true);
                    jFormattedTextFieldNgayDi.setEnabled(true);
                    jFormattedTextFieldNgayVe.setEnabled(true);
                    jButtonTimVe.setEnabled(true);
                    jButtonDatVe1.setEnabled(false);
                    JOptionPane.showMessageDialog(this, "Không tìm được tàu phù hợp");
                }
                    boolean timDuocItNhat1Tau=false;
                    for (TauChayTuyen j:DSTau)
                {
                    TauChayTuyen tauPhuHop=ketNoiCSDL.getTauPhuHop(i,j.getMaTau(), j.getThoiGianKhoiHanh(), strNgayDi);
                    if (tauPhuHop!=null)
                    {
                    timDuocItNhat1Tau=true;
                    DSTauPhuHop_ChieuVe.add(tauPhuHop);
                    String thoiGianDi=tauPhuHop.getThoiGianDenTramDi().toString();  
                    String thoiGianDen=tauPhuHop.getThoiGianDen().toString();
                    thoiGianDi=thoiGianDi.substring(0, thoiGianDi.length()-5);  //bỏ giây và mili giây
                    thoiGianDen=thoiGianDen.substring(0, thoiGianDen.length()-5);  //bỏ giây và mili giây
                    JTabbedPane jTabbedPaneTau=new JTabbedPane();
                    //JTabbedPaneDSTau.put(tauPhuHop.getMaTau(),jTabbedPaneTau);
                    jTabbedPane2.add(tauPhuHop.getMaTau(),jTabbedPaneTau);
                    DSToa=ketNoiCSDL.getToaTheoMaTau(tauPhuHop.getMaTau());
                    for (Toa l:DSToa)
                    {   
                        DSToaCuaTatCaTau_ChieuVe.add(l);
                        ArrayList<Integer> DSGheDaDat= ketNoiCSDL.getChoNgoiDaDat(tauPhuHop.getMaTau(), tauPhuHop.getThoiGianKhoiHanh(), l.getMaToa(), l.getThoiGianThemToa());
                        NewJPanel newJPanel;
                        switch (l.getSoChoNgoi()) {
                            case 80:
                                newJPanel=new JPanelNgoiCung80(tauPhuHop.getMaTau(),l.getMaToa(),thoiGianDi,thoiGianDen,model,jLabelChieuVe.getText(),DSGheDaDat);
                                jTabbedPaneTau.add(l.getMaToa(),newJPanel);
                                JTabbedPaneDSToa.put(l.getMaToa()+" "+thoiGianDi,newJPanel);
                                break;
                            case 56:
                                newJPanel=new JPanelNgoiMem56(tauPhuHop.getMaTau(),l.getMaToa(),thoiGianDi,thoiGianDen,model,jLabelChieuVe.getText(),DSGheDaDat);
                                JTabbedPaneDSToa.put(l.getMaToa()+" "+thoiGianDi,newJPanel);
                                jTabbedPaneTau.add(l.getMaToa(),newJPanel);
                                break;
                            case 42:
                                newJPanel=new JPanelGiuongNamKhoang642(tauPhuHop.getMaTau(),l.getMaToa(),thoiGianDi,thoiGianDen,model,jLabelChieuVe.getText(),DSGheDaDat);
                                JTabbedPaneDSToa.put(l.getMaToa()+" "+thoiGianDi,newJPanel);
                                jTabbedPaneTau.add(l.getMaToa(),newJPanel);
                                break;
                            case 28:
                                newJPanel=new JPanelGiuongNamKhoang428(tauPhuHop.getMaTau(),l.getMaToa(),thoiGianDi,thoiGianDen,model,jLabelChieuVe.getText(),DSGheDaDat);
                                JTabbedPaneDSToa.put(l.getMaToa()+" "+thoiGianDi,newJPanel);
                                jTabbedPaneTau.add(l.getMaToa(),newJPanel);
                                break;
                        }
                        }
                    }
                    else
                    {
                        if (timDuocItNhat1Tau=false) 
                        {
                            if (jLabelChieuDi.getText().equals("")) JOptionPane.showMessageDialog(this, "Không có tàu nào chạy trong ngày đã chọn!");
                            else
                            {
                                JOptionPane.showMessageDialog(this, "Không có tàu nào chạy "+jLabelChieuDi.getText().toLowerCase()+" trong ngày đã chọn!");
                                jRadioButton1Chieu.setEnabled(true);
                                jRadioButtonKhuHoi.setEnabled(true);
                            }
                            jButtonTimVe.setEnabled(true);
                            jButtonDatVe1.setEnabled(false);
                        }
                    }
                }
                }
            }
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Không được để trống. Hãy nhập ngày theo định dạng yyyy-MM-dd");
        }
        
        
        
    }//GEN-LAST:event_jButtonTimVeActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MousePressed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int dongDuocChon= jTable1.getSelectedRow();
        if (dongDuocChon!=-1)
        {
            if (jRadioButton1Chieu.isSelected())
            {
                String maToaCanXoa=model.getValueAt(dongDuocChon,1).toString();
                String soCuaChoNgoiCanXoa=model.getValueAt(dongDuocChon, 2).toString();
                String thoiGianDiCuaToaCanXoa=model.getValueAt(dongDuocChon,3).toString();
                NewJPanel jpnChuaChoNgoiCanXoa=JTabbedPaneDSToa.get(maToaCanXoa+" "+thoiGianDiCuaToaCanXoa);  //jpn chứa chỗ ngồi cần xoá
                jpnChuaChoNgoiCanXoa.enableJToggleButton(jpnChuaChoNgoiCanXoa.getJToggleButtonByText(soCuaChoNgoiCanXoa));//lấy JToggleButton rồi enable nó
                model.removeRow(dongDuocChon);
            }
            else
            {
                String maToaCanXoa=model.getValueAt(dongDuocChon,2).toString();
                String soCuaChoNgoiCanXoa=model.getValueAt(dongDuocChon, 3).toString();
                String thoiGianDiCuaToaCanXoa=model.getValueAt(dongDuocChon,4).toString();
                NewJPanel jpnChuaChoNgoiCanXoa=JTabbedPaneDSToa.get(maToaCanXoa+" "+thoiGianDiCuaToaCanXoa);  //jpn chứa chỗ ngồi cần xoá
                jpnChuaChoNgoiCanXoa.enableJToggleButton(jpnChuaChoNgoiCanXoa.getJToggleButtonByText(soCuaChoNgoiCanXoa));//lấy JToggleButton rồi enable nó
                model.removeRow(dongDuocChon);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng muốn xoá trong bảng!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
//        int indexTauDuocChon=jTabbedPane1.getSelectedIndex();
//        String maTauDuocChon=jTabbedPane1.getTitleAt(indexTauDuocChon);
//        for (TuyenDiQuaTram i:DSTuyen)
//        {
//            if (maTauDuocChon.equals(i.getM()))
//            {
//                jlbThoiGianDi.setText(formatThoiGianDi.format(i.getGioXuatTram()));
//            }
//        }
//    JOptionPane.showMessageDialog(this, jTabbedPane1.getTitleAt(jTabbedPane1.getSelectedIndex()));
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jRadioButton1ChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ChieuActionPerformed
        // TODO add your handling code here:
        jFormattedTextFieldNgayDi.setEnabled(true);
        jFormattedTextFieldNgayVe.setEnabled(false);
        jLabelChieuDi.setText("");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tàu", "Mã Toa", "Ghế Số", "Thời Gian Đi", "Thời Gian Đến"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(163);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(163);
        }
        
        //giao dien
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addGap(0, 0, 0)
        ));

        jScrollPane2.setViewportView(jPanel2);
        ///
    }//GEN-LAST:event_jRadioButton1ChieuActionPerformed

    private void jButtonDatVe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatVe1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1Chieu.isSelected())
        {
            for (int count=0;count<model.getRowCount();count++)
        {
            int doLechCot=0;
            if (jRadioButtonKhuHoi.isSelected()) doLechCot=1;
            String tempMaTau=model.getValueAt(count,0+doLechCot).toString();//Table---|maTau,maToa,i.getText(),thoiGianDi,thoiGianDen|
            String tempMaToa=model.getValueAt(count, 1+doLechCot).toString();
            int tempChoNgoiSo=Integer.valueOf(model.getValueAt(count, 2+doLechCot).toString());
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd hh:mm");
            Date tempThoiGianDi=null;
            try {
                tempThoiGianDi=formatter.parse(model.getValueAt(count, 3+doLechCot).toString());
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            Timestamp timeStampThoiGianDi=new Timestamp(tempThoiGianDi.getTime());
            Date tempThoiGianDen=null;
            try {
                tempThoiGianDen=formatter.parse(model.getValueAt(count, 4+doLechCot).toString());
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            Timestamp timeStampThoiGianDen=new Timestamp(tempThoiGianDen.getTime());
            //get Tuyến theo Mã Tàu
            TauChayTuyen tempTauChayTuyen=null;
            for (TauChayTuyen i:DSTauPhuHop)
            {
                if ((i.getMaTau().equals(tempMaTau))&&(i.getThoiGianDenTramDi().compareTo(timeStampThoiGianDi)==0))
                {
                    tempTauChayTuyen=i;
                    break;
                }
            }
            //get Trạm đi, Trạm đến theo Mã Tuyến
            TuyenDiQuaTram[] tempTuyenDiQuaTram=null;
            for (TuyenDiQuaTram[] i:DSTuyen)
            {
                if (i[0].getMaTuyen().equals(tempTauChayTuyen.getMaTuyen()))
                {
                    tempTuyenDiQuaTram=i;
                    break;
                }
            }
            Toa tempToa=null;
            for (Toa i:DSToaCuaTatCaTau)
            {
                if (i.getMaToa().equals(tempMaToa))
                {
                    tempToa=i;
                    break;
                }
            }
            int tempMaChuyen=ketNoiCSDL.addChuyenDi(tempTauChayTuyen.getMaTuyen(), tempTuyenDiQuaTram[0].getTenTram(), tempTuyenDiQuaTram[0].getThoiGianThemTram(), tempTuyenDiQuaTram[1].getTenTram(),tempTuyenDiQuaTram[1].getThoiGianThemTram(),tempMaTau,tempTauChayTuyen.getThoiGianKhoiHanh(),tempToa.getMaToa(),tempToa.getThoiGianThemToa());
            int tempMaVe=ketNoiCSDL.addVe(taiKhoan.getTenTaiKhoan(), tempChoNgoiSo, timeStampThoiGianDi, timeStampThoiGianDen, 0, false,tempMaChuyen);
            if (tempMaVe!=-1)
            {
               JOptionPane.showMessageDialog(this, "Thêm Vé 1 chiều thành công!");
            }
        }
        }
        if (jRadioButtonKhuHoi.isSelected())
        {
                Vector<Vector> dataTable=model.getDataVector();
//              System.out.println(dataTable.elementAt(i));
                new JDialogTaoCapVeKhuHoi(dataTable,DSTuyen,DSTuyen_ChieuVe,DSTauPhuHop,DSTauPhuHop_ChieuVe,DSToaCuaTatCaTau,DSToaCuaTatCaTau_ChieuVe,taiKhoan, true).setVisible(true);
                
        }
        
        
    }//GEN-LAST:event_jButtonDatVe1ActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jComboBoxGaDi.setSelectedIndex(0);
        jComboBoxGaDen.setSelectedIndex(0);
        if (!jFormattedTextFieldNgayDi.getText().equals("")) 
        {
            jFormattedTextFieldNgayDi.setText("");
            jFormattedTextFieldNgayDi.setEnabled(true);
        }
        if (!jFormattedTextFieldNgayVe.getText().equals("")) 
        {
            jFormattedTextFieldNgayVe.setText("");
            jFormattedTextFieldNgayVe.setEnabled(true);
        }
        jTabbedPane1.removeAll();
        if (jRadioButtonKhuHoi.isSelected()) jTabbedPane2.removeAll();
        model.setRowCount(0);
        jButtonTimVe.setEnabled(true);
        DSTauPhuHop.clear();
        DSToaCuaTatCaTau.clear();
        jRadioButton1Chieu.setEnabled(true);
        jRadioButtonKhuHoi.setEnabled(true);
        
    }//GEN-LAST:event_jButtonResetActionPerformed
//    public String TimMaTramTuongUng(String tenTram)
//    {
//        for (Tram i:DSTram)
//        {
//            if (i.getTenTram().equals(tenTram)) return i.getMaTram();
//        }
//        return "";
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupChonChieuDi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDatVe1;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonTimVe;
    private javax.swing.JComboBox<String> jComboBoxGaDen;
    private javax.swing.JComboBox<String> jComboBoxGaDi;
    private javax.swing.JFormattedTextField jFormattedTextFieldNgayDi;
    private javax.swing.JFormattedTextField jFormattedTextFieldNgayVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelChieuDi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1Chieu;
    private javax.swing.JRadioButton jRadioButtonKhuHoi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlbThoiGianDi;
    // End of variables declaration//GEN-END:variables
}
