/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.datve;

import java.util.ArrayList;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tuong
 */
public class JPanelGiuongNamKhoang428 extends NewJPanel {

    /**
     * Creates new form JPanelGiuongNamKhoang4
     */
    public JPanelGiuongNamKhoang428(String maTau, String maToa,String thoiGianDi,String thoiGianDen, DefaultTableModel model,JRadioButton jRadio1Chieu, String chieuDi, ArrayList<Integer> DSGheDaDat, int donGia) {
        super(maTau,maToa,thoiGianDi, thoiGianDen,model,jRadio1Chieu, chieuDi, DSGheDaDat, donGia);
        initComponents();
        jTextField1.setText(thoiGianDi);
        jTextField2.setText(thoiGianDen);
        listButton=new ArrayList<JToggleButton>();
        listButton.add(jToggleButton1);
        listButton.add(jToggleButton2);
        listButton.add(jToggleButton3);
        listButton.add(jToggleButton4);
        listButton.add(jToggleButton5);
        listButton.add(jToggleButton6);
        listButton.add(jToggleButton7);
        listButton.add(jToggleButton8);
        listButton.add(jToggleButton9);
        listButton.add(jToggleButton10);
        listButton.add(jToggleButton11);
        listButton.add(jToggleButton12);
        listButton.add(jToggleButton13);
        listButton.add(jToggleButton14);
        listButton.add(jToggleButton15);
        listButton.add(jToggleButton16);
        listButton.add(jToggleButton17);
        listButton.add(jToggleButton18);
        listButton.add(jToggleButton19);
        listButton.add(jToggleButton20);
        listButton.add(jToggleButton21);
        listButton.add(jToggleButton22);
        listButton.add(jToggleButton23);
        listButton.add(jToggleButton24);
        listButton.add(jToggleButton25);
        listButton.add(jToggleButton26);
        listButton.add(jToggleButton27);
        listButton.add(jToggleButton28);
        
        for (JToggleButton i:listButton)
        {
//            if (i.isSelected())
//            {
//                listGheDaChon.add(i.getText());
//            }
            i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtoniActionPerformed(i);
            }
        });
        }
        if (DSGheDaDat.size()!=0) disableJToggleButton();
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton23.setText("23");
        jToggleButton23.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton23ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 64, 30, 30));

        jToggleButton21.setText("21");
        jToggleButton21.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 114, 30, 30));

        jToggleButton22.setText("22");
        jToggleButton22.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 114, 30, 30));

        jToggleButton24.setText("24");
        jToggleButton24.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 64, 30, 30));

        jToggleButton25.setText("25");
        jToggleButton25.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 114, 30, 30));

        jToggleButton26.setText("26");
        jToggleButton26.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 114, 30, 30));

        jToggleButton27.setText("27");
        jToggleButton27.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 64, 30, 30));

        jToggleButton28.setText("28");
        jToggleButton28.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 64, 30, 30));

        jToggleButton4.setText("4");
        jToggleButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 64, 30, 30));

        jToggleButton3.setText("3");
        jToggleButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 64, 30, 30));

        jToggleButton7.setText("7");
        jToggleButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 64, 30, 30));

        jToggleButton8.setText("8");
        jToggleButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 64, 30, 30));

        jToggleButton11.setText("11");
        jToggleButton11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 64, 30, 30));

        jToggleButton12.setText("12");
        jToggleButton12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 64, 30, 30));

        jToggleButton15.setText("15");
        jToggleButton15.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 64, 30, 30));

        jToggleButton16.setText("16");
        jToggleButton16.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 64, 30, 30));

        jToggleButton19.setText("19");
        jToggleButton19.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 64, 30, 30));

        jToggleButton20.setText("20");
        jToggleButton20.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 64, 30, 30));

        jToggleButton2.setText("2");
        jToggleButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 114, 30, 30));

        jToggleButton1.setText("1");
        jToggleButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 114, 30, 30));

        jToggleButton5.setText("5");
        jToggleButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 114, 30, 30));

        jToggleButton6.setText("6");
        jToggleButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 114, 30, 30));

        jToggleButton9.setText("9");
        jToggleButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 114, 30, 30));

        jToggleButton10.setText("10");
        jToggleButton10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 114, 30, 30));

        jToggleButton13.setText("13");
        jToggleButton13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 114, 30, 30));

        jToggleButton14.setText("14");
        jToggleButton14.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 114, 30, 30));

        jToggleButton17.setText("17");
        jToggleButton17.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 114, 30, 30));

        jToggleButton18.setText("18");
        jToggleButton18.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel3.add(jToggleButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 114, 30, 30));

        jLabel45.setText("Tầng 1");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 124, -1, -1));

        jLabel46.setText("Tầng 2");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

        jLabel1.setText("Đi lúc:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 40, -1));

        jLabel2.setText("Đến lúc:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jTextField2.setEnabled(false);
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 237, 180, -1));

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 207, 180, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
